Axelrod-Python/Axelrod

axelrod/strategies/grudger.py
Added a short line of docstring to grudger
=> Added docstring to Grudger's strategy method

axelrod/strategies/__init__.py, axelrod/strategies/grumpy.py, axelrod/tests/test_grumpy.py
Adding grumpy. This strategy chooses a strategy based on two thresholds which depend on the history of the opponent.
=> Adding grumpy.py

axelrod/strategies/__init__.py, axelrod/strategies/inverse.py
I've created a new strategy for the Axelrod repo.  
Just beginning to learn about Python and Git/Github and your G+ post popped up so I thought I'd have a go - I've tested the code locally as much as I can.
=> Karlos78 patch 1

axelrod/strategies/__init__.py, axelrod/strategies/forgiver.py, axelrod/tests/test_forgiver.py
I've added a Forgiving Tit For Tat strategy and I've written unittests for it.
=> Forgiving Tit For Tat

run_tournament.py
Uses the argsparse module to add command line arguments
use `python run_tournament.py -h` to view the options
running it without any options defaults to the current settings.
=> adds command line arguments

axelrod/strategies/__init__.py, axelrod/strategies/mindreader.py, axelrod/tests/test_mindreader.py
Adding suggested change from https://github.com/drvinceknight/Axelrod/pull/34 to address https://github.com/drvinceknight/Axelrod/issues/22
=> Added a fix to mind reader so it can play geller, and tested that it can

axelrod/strategies/__init__.py, axelrod/strategies/mindcontrol.py, axelrod/tests/test_mindcontrol.py
This strategy takes control of the opponents strategy method and changes it to cooperate. It does rather well.
=> Added mind control strategies with tests

axelrod/strategies/retaliate.py, axelrod/tests/test_retaliate.py
Now with shiny new reset method
=> Adds Limited retaliate strategy

axelrod/strategies/__init__.py
Not sure how this went AWOL in the merge revert, but here it is again anyway
=> Adds limitedRetaliate to strategies

axelrod/strategies/mindcontrol.py, axelrod/strategies/mindreader.py, axelrod/tests/test_tournament.py, axelrod/tournament.py, run_tournament.py
I've refactored Axelrod slightly to create a Tournament and RoundRobin class and altered run_tournament.py (and a couple of strategies) to use it.
run_tournament.py is working fine, but the test suite needs a lot of changes and I haven't done that yet.
Let me know if you think this looks worthwhile and I'll go through the tests and alter them to fit.
=> Creates Tournament class

axelrod/tests/test_game.py, axelrod/tests/test_player.py, axelrod/tests/test_round_robin.py, axelrod/tests/test_tournament.py
=> splits test_tournament.py into separate files for each class under test

axelrod/tests/test_game.py, axelrod/tests/test_player.py, axelrod/tests/test_round_robin.py, axelrod/tests/test_tournament.py
For methods in those classes that had no test
=> Adds tests for game, player, round robin and tournament

run_tournament.py
=> adds argument to name cache file

setup.py
=> adds additional email addresses

README.rst
Just adding a badge and a graph to the readme file which points at https://waffle.io/Axelrod-Python/Axelrod
I don't know how useful this is but it also throws in a plot about PRs and issues.
=> Adding to waffle

README.rst, docs/usage.rst
Not sure how everyone feel about this? I have just been playing with asciicasts and honestly feel that it's the coolest thing I've ever seen... (but I have been known to show over enthusiasm in the past...)
=> Adding an ascii cast.

CHANGES.txt, setup.py
Just the basic changes ready to send up to pypi.
=> Ready for v0.0.8

axelrod/tournament_manager.py
Just added a dpi kwarg for the matplotlib save_fig function.
=> Increase DPI of generated plots for better resized resolution

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/test_titfortat.py
A strategy that always plays the opposite of the opponents previous move.
=> New Strategy Anti Tit For Tat

axelrod/strategies/alternator.py, axelrod/strategies/appeaser.py, axelrod/strategies/averagecopier.py, axelrod/strategies/cooperator.py, axelrod/strategies/defector.py, axelrod/strategies/forgiver.py, axelrod/strategies/gobymajority.py, axelrod/strategies/grudger.py, axelrod/strategies/grumpy.py, axelrod/strategies/hunter.py, axelrod/strategies/inverse.py, axelrod/strategies/mathematicalconstants.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/oncebitten.py, axelrod/strategies/punisher.py, axelrod/strategies/qlearner.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/strategies/titfortat.py
So I went through and tagged strategies as memory-one or not (with a boolean class member variable) giving either the four probabilities defining a strategy as memory-one (if it wasn't derived from the MemoryOnePlayer class explicitly) or an explanation of why the strategy is not memoryone.
The class var isn't used for anything yet.
=> Memory-one labels Re: Issue #170

.travis.yml, README.rst
=> Coverage Again

docs/overview_of_strategies.rst
=> Fixing the rendering of the code for Feld and Davis

docs/background.rst
Had the wrong score for defection again cooperation and vice versa.
=> Fixing the table - this addresses #216.

docs/overview_of_strategies.rst
#199
I'm not sure if "Hard Majority" is implemented in the library or not. I'll work on adding Hard TFT and Hard TF2T.
Does anyone know what "CALCULATOR" is or any of the PROBE strategies?
=> Documentation for New Strategies

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_titfortat.py, docs/overview_of_strategies.rst
It would be easy to parameterize HARD_TFT to look N rounds back, and to make Hard_TFNT to look for N consecutive defections in the last N+1 rounds.
=> HARD_TFT and HARD_TF2T

docs/overview_of_strategies.rst
=> HARD_JOSS is Joss

axelrod/strategies/memoryone.py, axelrod/tests/unit/test_memoryone.py, docs/overview_of_strategies.rst
This version is from Nowak's "Evolutionary Dynamics" and is more likely to be the one used in various tournaments than the existing implementation.
=> Update GTFT to the 'standard' version

axelrod/round_robin.py, axelrod/tests/unit/test_round_robin.py, axelrod/tournament_manager_factory.py
=> Removes mutable default arguments

axelrod/strategies/averagecopier.py, axelrod/strategies/cooperator.py, axelrod/strategies/defector.py, axelrod/strategies/forgiver.py, axelrod/strategies/hunter.py, axelrod/strategies/inverse.py, axelrod/strategies/mindcontrol.py, axelrod/strategies/rand.py, axelrod/strategies/titfortat.py, axelrod/tournament.py, axelrod/tournament_manager.py
=> Changes instance methods to static methods where possible

update_results.sh
No files are written to root of directory.
@marcharper probably best you just double check that I didn't miss a particular reason why the files needed to head over to the root directory :)
=> Updating the results script.

README.rst
It is possible that the list of projects could grow and we need to move
elsewhere. I suggest that if that's the case (a delightful problem to
have) we figure out the best place then.
Let me know if you think this is ok :)
=> Adding objectives and list of projects addressing #251

README.rst
Just adding a link to @marcharper's repository. Marc, should really be the one to say that this is ok: feel free to change/close without merging Marc, I just had some time so threw this together :)
=> Adding Marc's repository to readme

axelrod/strategies/darwin.py
=> Update reset function in Darwin to prevent bug when interacting with ForgivingTitForTat

README.rst
Adds a link to the Axelrod category on my blog.
=> Adds project to Readme

axelrod/tournament_manager.py
Closes #261 (?) and gets us ready to generate SVG plots in the new tournament branch.
=> Change image format to SVG

README.rst, docs/usage.rst
Basically streamlining various things.
=> For - 265 updating the README

docs/usage.rst
=> adds documentation section for cooperation matrix

requirements.txt
As pointed out by #158 we now use numpy so am adding it to the requirements.txt. **Wait to make sure that travis passes** I know that numpy can make things temperamental sometimes...
=> Adding numpy to the requirements.txt

axelrod/round_robin.py
=> adds tournament length to player2 on self-interactions

axelrod/strategies/_strategies.py, axelrod/strategies/cycler.py, axelrod/strategies/oncebitten.py, axelrod/tests/unit/test_cycler.py, axelrod/tests/unit/test_oncebitten.py, docs/overview_of_strategies.rst
Some additional strategies that behave cyclically and non-cyclically. There are now multiple strategies that hunt for other strategies that use patterns or cycles, but not that many strategies that actually behave in such a way.
This is post-deletion of assets #276.
=> New strategies

axelrod/player.py, axelrod/round_robin.py, axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/backstabber.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
=> Creates tournament attributes dictionary for players

docs/_static/usage/basic_strategies_20_turns_50_repetitions.svg, docs/_static/usage/basic_strategies_scaled_games.svg, docs/usage.rst
- Adding an example and plot for different turns and repetitions
- Adding a different game example
- For both of those am also including a new plot
=> Adding docs for non default arguments

docs/usage.rst
=> Adding comment about requirements.txt

.travis.yml
Let's see if Travis can handle the new Python 3.5 release.
=> Add Python 3.5 to .travis.yml

axelrod/game.py, axelrod/player.py, axelrod/strategies/darwin.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/mindreader.py, axelrod/strategies/qlearner.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_player.py, axelrod/tournament.py
This addresses #305. Perhaps not the most elegant solution -- comments welcome!
=> Properly use tournament attributes

docs/background.rst, docs/conf.py
I have checked readthedocs and this does not break that so this is a simple one.
=> Addresses 328: Adding the axelrod absolute path for autodoc.

axelrod/strategies/darwin.py, axelrod/tests/unit/test_darwin.py
#323 Introduced a bug into Darwin which this PR fixes.
=> Fix Darwin outcome attribute

README.rst
=> Adding comment about installing matplotib on ubuntu.

axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/cycler.py, axelrod/strategies/gobymajority.py, axelrod/strategies/grumpy.py, axelrod/strategies/memoryone.py, axelrod/strategies/oncebitten.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/tests/unit/test_player.py
=> Add explanations of parameters to docs strings of various strategies __init__ methods

axelrod/strategies/__init__.py, axelrod/strategies/_strategies.py, axelrod/strategies/calculator.py, axelrod/strategies/hunter.py, axelrod/strategies/meta.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_calculator.py, axelrod/tests/unit/test_hunter.py, axelrod/tests/unit/test_meta.py, axelrod/utils.py
Also: improved the Meta player tests and classifier handling, and added some additional tests.
I will rebase post #340...
=> New Strategies -- CycleHunter and multiple Meta strategies

axelrod/__init__.py, axelrod/cooperation.py, axelrod/payoff.py, axelrod/result_set.py, axelrod/tests/unit/test_cooperation.py, axelrod/tests/unit/test_payoff.py, axelrod/tests/unit/test_resultset.py
This is pre-work for #284. It takes the existing methods from the ResultSet class and creates new top-level functions instead.
It also includes a function to generate a payoff matrix from the interaction history. That function is, as yet, unused but shows how the RoundRobin will eventually return its results.
There should be no effect on the way the library currently works.
=> Pre-Work for #284

axelrod/strategies/memoryone.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_memoryone.py
This is some small cleanup of code. The biggest change is moving `WinStayLoseShift` to be a `MemoryOnePlayer` subclass. This offers less code duplication. Thoughts?
=> some small code cleanup

axelrod/player.py, axelrod/strategies/cycler.py, axelrod/strategies/memoryone.py, axelrod/strategies/rand.py, axelrod/strategies/titfortat.py, docs/contributing.rst
Follow-ups from Tuesday's discussions.
=> Some simple additions to the documentation

docs/usage.rst
Need to assign to ranks variable or this would not work.
Once the docs are re-written and doctested this shouldn't happen
again...
=> 1 line change to the docs.

axelrod/strategies/appeaser.py, axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/darwin.py
Follow up pull request after "Minor neatening of some strategies #361 " caused conflicts.
Darwin strategy: neaten use class variable
Strategies that use opponent.history should check opponent.history exists not self.history
Where possible @static decorator added to strategy method.
=> Minor neatening of some strategies

axelrod/plot.py, axelrod/tests/unit/test_plot.py, docs/usage.rst
- Adding depreciation warning in case of old system
- Change docs
- Adjusting tests.
This is my attempt at #349, having looked at things a bit closer getting rid of the argument all together implies passing the tournament object between all these things which is messy (I have a branch where that is implemented).
This seemed more elegant and just changes the input argument to be the whole ecosystem (which is slightly clearer from a ui pov). As people are beginning to use this library I've included a depreciation warning. :shipit:
=> Changing stackplot input

axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/geller.py, axelrod/strategies/inverse.py, axelrod/strategies/memoryone.py, axelrod/strategies/rand.py, axelrod/tests/unit/test_axelrod_tournaments.py, axelrod/tests/unit/test_inverse.py
This PR settles on using random_choice over any custom random.random logic.
=> use random_choice over many calls of random.random

axelrod/cooperation.py, axelrod/payoff.py, axelrod/result_set.py, axelrod/tests/unit/test_cooperation.py, axelrod/tests/unit/test_payoff.py
1. Refactors payoff_matrix to use interactions dictionary instead of matrix
2. Adds cooperation_matrix function to return cooperation matrix from interactions dictionary
3. Tidies up docstrings in both files
=> Refactors payoff.py and cooperation.py

axelrod/__init__.py, axelrod/actions.py, axelrod/player.py, axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_actions.py
I saw a few instances where this function could be useful (I found it useful implementing my v1 of a person IPD project.). There are probably some more instances in other strategies. 
Couple things: 1) I'm so-so on the name `reverse_action` - I'm happy to hear other suggestions. 2) This changes the implementation of TitFotTat to something I think it more readable. 
Thoughts?
=> adding a reverse_action function

axelrod/strategies/titfortat.py, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst
This addresses #382 and make TitForTat verbose.
=> 382 - Make TitForTat verbose

axelrod/tournament_manager.py, requirements.txt
Quick fix for #391 using cloudpickle. Please see the discussion at #391.
=> Pickle fix

axelrod/strategies/_strategies.py
Somewhere in the rebasing this got lost.
=> Add OmegaTFT to strategies list

axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/advanced/strategy_transformers.rst, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst, doctest
This is an update to the strategy transformers to use a class to better handle arguments in transformers. 
Edit: removed discussion of #391 re: #392
=> Rework strategy transformers and documentation.

docs/citing_the_library.rst, docs/index.rst
- Thrown it at the root of the docs (wasn't sure where else to go).
- Still pointing at the project site (is this what we want?).
=> Adding citation of library to docs.

axelrod/player.py, axelrod/strategies/backstabber.py, axelrod/strategies/oncebitten.py, axelrod/strategies/punisher.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_apavlov.py, axelrod/tests/unit/test_cooperator.py, axelrod/tests/unit/test_defector.py, axelrod/tests/unit/test_ecosystem.py, axelrod/tests/unit/test_forgiver.py, axelrod/tests/unit/test_geller.py, axelrod/tests/unit/test_gobymajority.py, axelrod/tests/unit/test_grudger.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_meta.py, axelrod/tests/unit/test_mindcontrol.py, axelrod/tests/unit/test_mindreader.py, axelrod/tests/unit/test_oncebitten.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_prober.py, axelrod/tests/unit/test_punisher.py, docs/tutorials/advanced/strategy_transformers.rst, docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
Simplifies some tests using the new `attrs` option in `TestPlayer.test_responses`.
=> Update and simplify some tests; Correct attrs testing and add info to docs

README.rst
Not sure if this is needed... (Order is alphabetical based on github handle)
=> Adding list of core contribs

axelrod/tests/unit/test_headsup.py, axelrod/tests/unit/test_lookerup.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_titfortat.py
Also uncommented and modified a strategy transformer test.
=> Refactor HeadsUpTest to be more intuitive, more flexible, more like test_responses

README.rst
Links work fine on my branch, merging as discussed in gitter.
=> Add mojones's blog post to the readme

axelrod/strategies/lookerup.py, axelrod/tests/unit/test_lookerup.py
I re-ran the evolutionary algorithm to take account of the recently-added strategies.
=> Update pattern string

README.rst
=> Adding width to images.

README.rst
Fixed a link and added my recent blog posts to the projects section.
=> Readme Updates

docs/conf.py
Code from http://read-the-docs.readthedocs.org/en/latest/theme.html to use their default sphinx theme
=> Use RTD sphinx theme

docs/reference/overview_of_strategies.rst
Some very minor updates to the documentation.
=> Some updates and corrections to the docs

axelrod/strategies/mindreader.py
This is from an experimental branch a few months back to remove the deepcopy in mindreader. It fixes one of the bugs in #465 but is also much slower overall (running a few tournaments to verify timing, will edit with results). I simply rebased onto the latest master and squashed in a few fixes (e.g. `update_history` versus `update_histories`). The other bug is fixed in #469.
One possible downside is that this method doesn't necessarily copy stochastic players exactly because the history of play might change when the history is replayed. OTOH that may be a feature -- an advanced mindreader might run its experiments many times to determine the next best move.
=> Eliminate use of copy.deepcopy in mindreader

axelrod/player.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/backstabber.py, axelrod/strategies/grudger.py, axelrod/strategies/hunter.py, axelrod/strategies/meta.py, axelrod/strategies/oncebitten.py, axelrod/tests/unit/test_meta.py
Mostly static methods that were unmarked.
=> Some Changes suggested by Quantified code

axelrod/tests/unit/test_tournament.py, axelrod/tests/unit/test_tournament_type.py, axelrod/tournament.py, axelrod/tournament_type.py
#413 Create a TournamentType class and RoundRobin class in order to clone players once at the Tournament level rather than once per repetition
=> Re-introducing RoundRobin

axelrod/utils.py
=> Only instantiate the logHandler in use

axelrod/tests/unit/test_tournament.py
This follows the comment here by @marcharper:
https://github.com/Axelrod-Python/Axelrod/pull/474#discussion_r55115176
=> Hypothesis'ing one test.

axelrod/match.py, axelrod/tests/unit/test_match.py, docs/tutorials/further_topics/creating_matches.rst
Just adds a method to score the results of a Match.
=> Add scores method to Match class

axelrod/strategies/gobymajority.py, axelrod/tests/unit/test_gobymajority.py
I moved the name to the init.
Also included a few more tests.
=> Fixing #500

axelrod/strategies/lookerup.py, axelrod/tests/unit/test_lookerup.py
=> Catch self.plays == 0 corner case of LookerUp

axelrod/strategies/memoryone.py, axelrod/tests/unit/test_memoryone.py
This addresses #506.
I'm going to open an issue to make sure we check this for other strategies.
I briefly tried to add the test I added for `WSLS` to the player class but didn't get a failure so the issue I open will investigate that.
=> Fix classification of wsls.

docs/citing_the_library.rst
I used md syntax out of habit.
=> Minor: Fixing the hyperlink.

axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/conf.py, requirements.txt
#518
Also add a module definition to decorated classes so that they can be pickled
=> Replace multiprocessing with multiprocess

axelrod/__init__.py, axelrod/match.py, axelrod/match_generator.py, axelrod/plot.py, axelrod/result_set.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/making_tournaments.rst, docs/tutorials/getting_started/interactions.rst
#526 
I also make a very minor change to the results and plots classes: I allow them to deal with missing values: so cases where a player doesn't not actually play a match (they get a score of 0). This is based on the simple tournament I build in the tutorial, where match ups occur with a given probability.
=> `tournament_type` -> `match_generator` #526

axelrod/deterministic_cache.py, axelrod/match.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_match.py, axelrod/tests/unit/test_tournament_manager.py, axelrod/tournament_manager.py
=> Adds match length to deterministic cache key

axelrod/match_generator.py
=> Remove line to set cache mutabilty to false

axelrod/moran.py, axelrod/tests/unit/test_moran.py
Also fix a bug in the reset function.
=> Add deterministic cache to Moran process an a bug fix

axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
Closes #555
Also removed test and method that can now just inherit from base class.
=> Prob End Tournament can now take a cache

axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
@marcharper : Most of these were just changing the inputs to the tests so that they work with your new setup.
I could also remove two tests as they were testing methods that are not there anymore.
This could probably be tidied up more but they're all passing and testing the right things (I think).
I didn't look too close at the code/changes you made, just got the tests right :) :+1:
=> Not for master: Fixing tests

requirements.txt
=> Pinning pyparsing in requirements.txt.

axelrod/_strategy_utils.py, axelrod/deterministic_cache.py, axelrod/match_generator.py, axelrod/moran.py, axelrod/plot.py, axelrod/strategies/apavlov.py, axelrod/strategies/qlearner.py, axelrod/tests/unit/test_apavlov.py, axelrod/tests/unit/test_axelrod_first.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_retaliate.py, axelrod/tests/unit/test_strategy_utils.py
This adds various tests and removes some things to improve the test coverage. As is the only lines of code that are not tested are for when matplotlib is not installed:
```
Name                                  Stmts   Miss  Cover   Missing
-------------------------------------------------------------------
__init__.py                              15      0   100%   
_strategy_utils.py                       68      0   100%   
actions.py                                9      0   100%   
deterministic_cache.py                   48      0   100%   
ecosystem.py                             34      0   100%   
eigen.py                                 30      0   100%   
game.py                                  16      0   100%   
interaction_utils.py                     55      0   100% …
```
=> 581 - Improving test coverage

axelrod/plot.py, axelrod/tests/unit/test_plot.py
=> Adding ability to turn log scale off.

docs/tutorials/further_topics/probabilistict_end_tournaments.rst
Closes #613
Clarifying a paragraph noted by reviewer of paper.
=> Fixing docs for prob end

axelrod/tests/unit/test_hunter.py
There was a line of the hunter module that was not getting hit. This gets it (just to improve coverage every so slightly).
=> Adding a test for a line that was not covered.

requirements.txt
=> Removing testfixtures.

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_titfortat.py
=> Adding Gradual

LICENSE.txt, docs/tutorials/contributing/guidelines.rst
=> Copyright and licence stuff

axelrod/tests/property.py, axelrod/tests/unit/test_match.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_property.py, axelrod/tests/unit/test_tournament.py, requirements.txt
Closes #604.
This is possible since hypothesis 3.2
=> Removing the random module for hypothesis

docs/community.rst, docs/index.rst
Very basic: just trying to say we're friendly and where to find us. 
Closes #644
=> Adds a community page.

docs/tutorials/advanced/setting_a_seed.rst
I am not entirely sure why the output changed. The results still repeat
so the seed works.
=> Fixing seed.

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
Closes #661 
The result set takes a game and the tournament is able to pass it a game.
=> Non default games fixed

axelrod/player.py, axelrod/strategies/cycler.py, axelrod/strategies/gobymajority.py, axelrod/strategies/retaliate.py, axelrod/tests/integration/test_names.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_player.py
- Ensures that each Strategy class has a unique name (required for the API)
- Fixes some PEP8 errors
=> Strategy names and PEP8

axelrod/strategies/__init__.py, axelrod/strategies/_filters.py, axelrod/tests/integration/test_filtering.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_filters.py, docs/tutorials/advanced/classification_of_strategies.rst
This code fixes #696 
I've not written the documentation yet, which is why this PR is not ready to merge.
I'd appreciate thoughts and comments on the code and the tests. Once we're happy with those, I'll finish off the PR by completing the documentation.
=> Filtering Strategies

CHANGES.md
=> Correct diff link.

axelrod/tournament.py
=> Fix for windows CSV writer newline issue.

docs/citing_the_library.rst
=> Fix Link to citations

.gitignore
Based on https://github.com/github/gitignore/blob/master/Python.gitignore
=> Add standard python content to .gitignore

.gitignore, axelrod/plot.py, axelrod/tests/unit/test_plot.py, docs/tutorials/getting_started/visualising_results.rst
Closes #708.
Note that this does not create the eco plot.
=> Create a `save_all_plots` for the axl.Plot class

axelrod/random_.py, axelrod/tests/unit/test_axelrod_second.py, axelrod/tests/unit/test_headsup.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_random_.py
Closes #760
- Test included to check that random seed is not offset
- Adjusted some remaining tests (surprisingly, not that many!)
=> Stop random_choice sampling when used with 0 or 1

README.rst
Also adding a link to my own github repo.
=> Updating the list of core devs.

axelrod/moran.py
=> Calculate score per turn using match method in the Moran process.

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py
~~This is branched from #767.~~ EDIT: That's no longer true. 
Closes #769
=> Add title option to fingerprint.plot 

axelrod/strategies/adaptive.py, axelrod/strategies/grudger.py, axelrod/strategies/handshake.py, axelrod/strategies/memoryone.py, axelrod/strategies/rand.py, axelrod/strategies/titfortat.py, docs/reference/bibliography.rst
A similar commit to my previous ones. Again on issue #225.
=> More strategies documentation

axelrod/strategies/rand.py, axelrod/tests/unit/test_rand.py
- Add a test for stochastic classification of Random
Closes #781
=> Reclassify Random player if p is 0 or 1

.travis.yml, docs/tutorials/further_topics/spatial_tournaments.rst
=> Change python support from 3.4/3.5 to 3.5/3.6

docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
This is a PR with a suggested restructure for the docs for the PR: #820 opened by @marcharper
=> Re structure testing docs.

axelrod/random_.py
=> Modify the docstring for random_choice.

README.rst
The readme is written in rst (not md) so that it renders on pypi.
=> Fix hyperlinks in the readme.

axelrod/strategies/appeaser.py
#808 
I did run checks with `mypy`, and it showed up no errors.
=> Add type hints to appeaser

appveyor.yml
=> Add 3.6 to appveyor.

axelrod/strategies/forgiver.py, type_tests.sh
#808 
@drvinceknight @marcharper
=> Add type hints to forgiver

axelrod/strategies/_strategies.py, axelrod/strategies/punisher.py, axelrod/tests/unit/test_punisher.py
The strategy is taken from CoopSim
=> New Strategy: Add LevelPunisher

axelrod/moran.py
=> Add type for Moran

axelrod/player.py, axelrod/strategies/adaptive.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/doubler.py, axelrod/strategies/gambler.py, axelrod/strategies/gobymajority.py, axelrod/strategies/mathematicalconstants.py, axelrod/strategies/memoryone.py, axelrod/strategies/qlearner.py, axelrod/strategies/retaliate.py, axelrod/strategies/sequence_player.py, axelrod/strategies/stalker.py, axelrod/strategies/titfortat.py, axelrod/strategies/worse_and_worse.py, type_tests.sh
#808
Only one error I am not able to resolve.
`axelrod_first.py:442: error: "type" has no attribute "memory_depth"`
=> Add type hints

axelrod/fingerprint.py, axelrod/plot.py, axelrod/strategies/human.py, axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_windows_detection.py, axelrod/tournament.py
Tell coverage to ignore lines that we know cannot be tested.
=> Coverage ignore instructions

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_tournament.py
This wasn't working correctly and had been missed as we were not
covering a line.
This should also improve the coverage score.
=> Fix bug in fingerprint with filename.

axelrod/graph.py, axelrod/tests/unit/test_graph.py
=> Add tests for Graph init

axelrod/plot.py, axelrod/tests/unit/test_plot.py
I also reverted back to use if statements, which felt simpler in this (2
option) case.
=> Use distutils version comparison.

axelrod/tests/unit/test_match_generator.py
Just to make it a bit more explicit. Sorry, should have raised it as a
discussion on the PR but only noticed after. Happy to change it to
something else.
=> Minor function rename.

axelrod/tests/strategies/test_player.py
I've added another 'no cover' pragma to fix this one or else we end up writing tests for our tests, which didn't seem entirely sensible. Happy to discuss!
=> Fix coverage of test_player.py

docs/tutorials/contributing/strategy/adding_the_new_strategy.rst
Here is how this page currently looks:
http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/adding_the_new_strategy.html
This PR will change the format style of two file paths.
=> A very minor rst syntax fix.

axelrod/strategies/hmm.py, run_mypy.py
#808 
I made some changes but i think there are more .
I will delte the 9-10 lines (comments).
I will do more tommorow !!!
=> Add Type hints to hmm 

axelrod/strategies/finite_state_machines.py, axelrod/strategies/hmm.py, axelrod/strategies/human.py, axelrod/strategies/prober.py, run_mypy.py
=> More type hints

axelrod/tests/strategies/test_finite_state_machines.py
I found a bug working with v2.8.0, but #956 seems to have cleared it up.
I'm just adding a test to confirm it.
I've also cleared up some minor PEP8 stuff.
=> Add an extra test for the FSM players

axelrod/tests/strategies/test_mutual.py
=> Refactoring mutual.py using versus_test

axelrod/tests/strategies/test_sequence_player.py
=> Refactor test for sequence player.

docs/tutorials/advanced/index.rst, docs/tutorials/advanced/tournament_results.rst, docs/tutorials/further_topics/approximate_moran_processes.rst, docs/tutorials/further_topics/morality_metrics.rst, docs/tutorials/getting_started/index.rst, docs/tutorials/getting_started/summarising_tournaments.rst, requirements.txt, rtd_environment.yml
Closes #985.
Also tweaked some minor stylistic issues.
=> Fragment the result set documentation.

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py, run_mypy.py
=> fingerprint methods to functions

axelrod/strategies/gobymajority.py, axelrod/tests/strategies/test_gobymajority.py
=> #884 gobymajority

axelrod/tests/strategies/test_gradualkiller.py
=> #884 gradualkiller

axelrod/strategies/grumpy.py, axelrod/tests/strategies/test_grumpy.py
=> 884-grumpy

docs/reference/play_contexts.rst, docs/tutorials/advanced/games.rst, docs/tutorials/advanced/index.rst
This came up as a question in the gitter channel.
=> Add a tutorial for using and modifying stage games

axelrod/strategies/memorytwo.py, docs/reference/bibliography.rst, docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
- A minor error in the test documentation
- Incorrect citation key for a paper by Li.
=> Fix minor bugs in documentation

requirements.txt
This upper bound is restrictive and not necessary. Also this aligns with #991.
=> Remove upper bound on tqdm version.

docs/tutorials/contributing/strategy/docstrings.rst
I suggest this doesn't need a second :+1:...
=> Add a blank line in docstring documentation.

axelrod/tests/strategies/test_retaliate.py
Also adding specific test for some of the parametrized versions.
Contributes towards #884
=> Refactor tests for retaliate.

axelrod/tests/strategies/test_qlearner.py
This is as closes to "as is" as possible. Note that we're able to
simplify the tests a lot using the `attrs` in `versus_test`.
=> Refactor the Q learner tests.

axelrod/tests/strategies/test_meta.py
=> Refactor tests for meta

axelrod/tests/unit/test_mock_player.py
This ensures we have a possible history being tested throughout.
Addresses #884.
=> Minor refactor of Mock Player tests

axelrod/tests/strategies/test_axelrod_first.py
https://github.com/Axelrod-Python/Axelrod/pull/1045 was merged before CI finished running and included a bug. Once travis is happy I will merge this.
=> Fix a broken test.

axelrod/strategies/memoryone.py, docs/reference/bibliography.rst
=> Include alternate name for AllCorAllD

docs/reference/overview_of_strategies.rst
As per investigation in https://github.com/Axelrod-Python/axelrod-fortran/issues/31
=> Mark Grofman's strategy as not implemented

axelrod/strategies/memoryone.py
I'd like us to not use these type declarations. One of Type hints
contributions is to
the readability of the code.
=> Minor: Make type hinting more verbose in memory one.

axelrod/strategies/axelrod_second.py
=> Use opponent.defections in Cave and some minor styling changes

axelrod/strategies/axelrod_second.py
=> Correct docstring for axl.Black.

axelrod/tests/unit/test_plot.py, doctests.py
~~A PR to try and identify where the actual problem is #1187 ~~
I have rerun the builds multiples times and (hesitantly but confidently) believe this closes #1191: thanks @marcharper for suggesting matplotlib!
=> Fix Inconsistant CI failures

axelrod/_strategy_utils.py, axelrod/tests/unit/test_strategy_utils.py
More changes for #347 
* Cleaned up and expand docstrings
* Made functions that are not used elsewhere internal
* Refactored look_ahead a bit to make it more readable
* Added more unit tests
=> Spruce up strategy utils module

axelrod/strategies/human.py, docs/conf.py, requirements.txt
=> Update library to work with prompt_toolkit >= 2.00

citations.md
Also updated some ArXiv citations that have been published.
=> Reorder citations by year and then alphabetically

.travis.yml, appveyor.yml, requirements.txt
=> Fix travis, appveyor, and bump python versions up to 3.6 and 3.7

axelrod/strategies/titfortat.py, docs/reference/overview_of_strategies.rst
From the code, it says (SAME AS ROUND ONE TIT FOR TWO TATS):
https://github.com/Axelrod-Python/TourExec/blob/v0.2.0/src/strategies/k90r.f
=> Label k90r, from Axelrod's second, is TitFor2Tats

citations.md
The algorithm is already implemented in the library :) :+1:
=> Add preprint on FSM memory algorithm.

docs/reference/bibliography.rst
=> Add a missing author to paper in bib

axelrod/strategies/zero_determinant.py
=> Improve and Expand LRPLayer docstring

axelrod/result_set.py, axelrod/tests/unit/test_eigen.py, axelrod/tests/unit/test_resultset.py
Fixes https://github.com/Axelrod-Python/Axelrod/issues/1286
=> Fix ResultSet __eq__ to handle nans

axelrod/result_set.py, axelrod/tests/unit/test_eigen.py, axelrod/tests/unit/test_resultset.py
Reverts Axelrod-Python/Axelrod#1301 since the latest tests did not pass
=> Revert "Fix ResultSet __eq__ to handle nans"

MANIFEST.in, setup.py
This is a bug fix. Will create a new release when it's in.
=> Fix broken data file imports.

citations.md
This adds this paper: https://www.aaai.org/Papers/AAAI/2020GB/AAAI-WangS.1218.pdf
=> Add Wang et al to citations.

README.rst
I've sorted our usernames alphabetically.
=> Update core contributors list.

.github/workflows/config.yml
=> Add weekly CI run.

axelrod/tests/ultimatum/tests.py, axelrod/ultimatum/player.py
This gives a more robust way of checking the player's history of offers and decisions.
=> Add history class to ultimatum

axelrod/strategies/dbs.py
=> Fix name in documentation of dbs strategy.

.github/workflows/config.yml, setup.py
=> Add python 3.8 to setup.py and github CI config
