Axelrod-Python/Axelrod

.editorconfig
A config file which controls text editor settings for those editors which support it. (e.g. indentation format, line ending characters)
More details at: http://editorconfig.org/
Plugins for supported editors here: http://editorconfig.org/#download
=> Adds use of editorconfig

axelrod/strategies/__init__.py, axelrod/strategies/retaliate.py, axelrod/tests/test_retaliate.py
I hit merge before I looked at the code. Sorry. This needs it's own `reset` method does it not? Otherwise the count and boolean won't be right? (They might be because of the strategy method but in that case I'd still like to see a test of what happens when it plays a second game: ideally it's own reset method would be ideal). Apologies if I'm missing something.
=> Revert "Adds Limited retaliate strategy"

.travis.yml, axelrod/strategies/geller.py, axelrod/strategies/gobymajority.py, axelrod/strategies/retaliate.py, docs/Makefile, docs/contributing.rst, docs/strategies.py, docs/strategies.rst
This is relevant to #92. 
I started wanting to change how things were done but ended up just doing some spring cleaning.
- I set the `Makefile` back to how it was before @langner's cool fix which sadly didn't work with readthedocs. I think we'll just have to run `python strategies.py > strategies.rst` when a new strategy gets included (this could also be added to the documentation...)
- I also added running the `strategies.py` script to travis (for example a change in the `_strategies.py` file actually broke this script). It doesn't do anything except check that it runs without any errors.
=> 92 strategy docs

README.rst, axelrod/strategies/memoryone.py
Very simple change to README.rst as I'm almost certain that Tit-for-Tat should not be expected to "win" the tournament if only there were more strategies. I'm also highly sceptical of the claims in the literature of the superiority of e.g. ZD-strategies as they make rather questionable assumptions (weak selection, arbitrarily long games, using stationary scores instead of the real payoff matrices, etc.) My own work with Chris Lee and Dashiell Fryer shows that non-memory-one strategies can be very effective, and the MetaHunter strategy in this repository is another good example (and much more simple).
In fact, I encourage you all to publish these results, perhaps computing things like mean score per round as the number of rounds gets large and other quantities. The literature is in sore …
=> Docs update -- removed suspect Tit-for-Tat statement

axelrod/tests/test_headsup.py, axelrod/tests/test_player.py, docs/contributing.rst
This PR adds a new class TestHeadsUp to test_player.py that takes two strategies and a list of expected rounds of play for testing. It's very similar to the last testing PR. Several examples are included in test_headsup.py and there's a short explanation of how to make more such tests on the contributions page.
=> Heads Up play tests

axelrod/strategies/alternator.py, axelrod/strategies/appeaser.py, axelrod/strategies/averagecopier.py, axelrod/strategies/cooperator.py, axelrod/strategies/darwin.py, axelrod/strategies/defector.py, axelrod/strategies/forgiver.py, axelrod/strategies/geller.py, axelrod/strategies/gobymajority.py, axelrod/strategies/grudger.py, axelrod/strategies/grumpy.py, axelrod/strategies/hunter.py, axelrod/strategies/inverse.py, axelrod/strategies/mathematicalconstants.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/oncebitten.py, axelrod/strategies/punisher.py, axelrod/strategies/qlearner.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_oncebitten.py
Fixes #223, strategies now have their memory_depth indicated as follows:
* 0 if the last round is irrelevant (ALLC, ALLD, and Random)
* 1 if the strategy is memory one
* n if the strategy uses the last n rounds (e.g. 2 for TitFor2Tats, 3 for HARD_TFT, various for GoByMajority)
* infinity aka float('inf') if the entire history is used or there is an internal bit of memory that can persist indefinitely.
* For Gellar, since it looks into the future, I set its memory_depth to -1.
While I was going through all the strategy files I made a few various updates e.g. for PEP8, and added in float(...) in a few places where it looked like there was unintentional integer division (e.g. in forgiver). Lastly, Darwin had a game matrix hard-coded, so I updated it to pull from the Game class.
(Edited to …
=> Replace memoryone with memory_depth, various PEP8, a few integer division corrections

docs/usage.rst
Once [this PR](https://github.com/Axelrod-Python/tournament/pull/1) is in, the SVG images should show properly in the Axelrod docs on this branch.
=> Update image URLs to tournament repository github.io

axelrod/strategies/gobymajority.py, axelrod/strategies/memoryone.py, axelrod/strategies/rand.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_gobymajority.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_rand.py, docs/contributing.rst
Just changes the display names of a few strategies so that multiple instances do not have the same name. For example, Random is now named "Random 0.5", and the name changes if you instantiate with different parameters. This way if you have multiple Random players (with different internal probabilities), they don't show up with the same name.
=> Display names

setup.py
It would seem that ``python setup.py develop`` is a command supported not supported by ``distutils``
Also, the ``install_requires`` kwarg is not supported by ``distutils``, although it's defined in setup.py
Both are supported by ``setuptools`` though, so it seems that replacing ``distutils`` for it is the answer.
Packaging is not my forte by any extend of the imagination though and I am unaware if changing this is going to kill the rest of the world (I doubt it though)
I particularly l leaned on this article when researching:
http://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2
=> Replace disutils for setuptools in setup.py

axelrod/player.py, axelrod/round_robin.py, axelrod/strategies/axelrod_tournaments.py, axelrod/strategies/cycler.py, axelrod/strategies/darwin.py, axelrod/strategies/gobymajority.py, axelrod/strategies/grumpy.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/mindreader.py, axelrod/strategies/oncebitten.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/tests/integration/test_round_robin.py, axelrod/tests/unit/test_mindreader.py, axelrod/tests/unit/test_player.py, docs/contributing.rst
Re: #303 
I added `self.init_args = ()` to `Player.__init__`. A child strategy that needs to pass through arguments need only set `self.init_args = (...)` (overriding `reproduce` is not necessary). I updated all the appropriate strategies and added tests.
=> Reproduce method for Player

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, docs/usage.rst
=> Adds wins to result set

axelrod/strategies/meta.py, axelrod/tests/unit/test_hunter.py, axelrod/tests/unit/test_meta.py
The MetaPlayer derived strategies retain state between games. I believe this is unintentional.
=> Update MetaPlayer reset to also reset team

axelrod/__init__.py
The script update_results.sh in the tournament repository doesn't run after the switch to explicit imports. This fixes it.
=> Fix implicit imports for tournament repo

axelrod/__init__.py, axelrod/player.py, axelrod/strategies/__init__.py, axelrod/strategies/meta.py, axelrod/tests/unit/test_classification.py, docs/contributing.rst, docs/usage.rst
Following on from the discussion on #343 which ended up being another discussion about cheaters. Have changed the `is_cheater` function to be `obey_axelrod` which makes things a bit less subjective (users can then include whatever strategies they want). 
At present it makes no difference to the library (although the tournament repository) but hopefully will clarify all future discussions about the incoming strategies.
I have added something to the documentation but waiting on #299 this is very minor.
=> 343 - Change name of is_cheater function.

README.rst, axelrod/payoff.py, axelrod/plot.py, axelrod/result_set.py, axelrod/tests/unit/test_payoff.py, axelrod/tournament_manager.py, docs/usage.rst
Two new plots:
* "*_sdvplot.svg" -- the score difference distributions in a violin plot
* "*_pdplot.svg" -- the score difference means in a heat map (like the payoff plot)
The new plots make it easier to see how a strategy is winning, either by mutual cooperation or successful defections. (Certainly the first one at least.)
Violin plots: these are a better representation of the actual distributions than boxplots in my opinion, so I updated the code to generate these instead. The downside is that matplotlib v1.4.3 doesn't handle them correctly in all cases, but there is a fix in for 1.5. So the code now catches an exception and falls back onto a boxplot if necessary.
Here's the noisy mean score distribution as a violin plot:
I also made various improvements to the plot sizes and spacing. …
=> More plots and various plotting improvements

.mailmap
This allows us to use tools like gitinspector to analyze the repository:
[Python contributions] (http://marcharper.codes/axelrod/axelrod_py.html)
* Owen Campbell 39.77%
* Marc Harper 23.47%
* Vincent Knight	 15.48%
* Karol M. Langner 10.75%
[Documentation Contributions](http://marcharper.codes/axelrod/axelrod_rst.html)
* Vincent Knight	 71.46%
* Marc Harper 21.76%
* Owen Campbell 3.01%
* Luis Visintini 2.19%
=> Add .mailmap file so that `git shortlog` groups names correctly

axelrod/payoff.py, axelrod/result_set.py, axelrod/tests/unit/test_payoff.py
1) Splits the payoff_matrix function into two, creating a new function: interaction_payoff which it then calls.
This gives us a function which can be used to obtain the scores for a single interaction of n turns between two players
2) Removes redundant parameters from various payoff functions where they can be derived from the payoff matrix.
=> Refactors payoff.py

docs/reference/glossary.rst, docs/tutorials/contributing/index.rst, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst, docs/tutorials/getting_started/getting_started.rst, docs/tutorials/getting_started/noisy_tournaments.rst, docs/tutorials/getting_started/payoff_matrix.rst, docs/tutorials/getting_started/visualising_results.rst
This fixes some bugs in docs but also (mainly) aims to try and address #313:
- Have added player/strategy to glossary
- Have gone through and tried to tweak as necessary
=> 313 - Address terms that are interchangeably used in documentation

axelrod/strategies/_strategies.py, axelrod/strategies/apavlov.py, axelrod/tests/unit/test_apavlov.py, axelrod/tests/unit/test_player.py, docs/reference/overview_of_strategies.rst, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst
Two new strategies, both variants of APavlov that won a 2005 IPD tournament.
Also added a kwarg `attrs` to test_responses, which is a dictionary of attributes to check at the end of testing the sequence of plays. This simplifies the testing of internal variables of strategies in significant situations, and should useful in many other places in the library.
=> Adaptive Pavlov, two versions

axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/advanced/strategy_transformers.rst
`RetaliateTransformer(N)`: Retaliation N times after a defection:
```
>>> import axelrod
>>> from axelrod.strategy_transformers import RetaliationTransformer
>>> TwoTitsForTat = RetaliationTransformer(2)(axelrod.Cooperator)
>>> player = TwoTitsForTat()
```
`ApologizingTransformer`: Apologizes after a round of `(D, C)`:
```
>>> import axelrod
>>> from axelrod.strategy_transformers import ApologyTransformer
>>> ApologizingDefector = ApologyTransformer([D], [C])(axelrod.Defector)
>>> player = ApologizingDefector()
```
`DeadlockBreakingTransformer`: Attempts to break `(D, C) -> (C, D)` deadlocks by cooperating:
```
>>> import axelrod
>>> from axelrod.strategy_transformers import DeadlockBreakingTransformer
>>> DeadlockBreakingTFT = DeadlockBreakingTransformer(axelrod.TitForTat)
>>> player = …
```
=> New transformers: Apologizing, Retaliating variant, Deadlock Breaking, Grudging

axelrod/tests/unit/test_titfortat.py, docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
- Correct test in documentation
- Adding docstring to the test class saying to leave it alone and/or
change the docs if you modify.
=> 400 - Aligning the documentation for the TitForTat test

axelrod/strategies/axelrod_first.py, axelrod/strategies/gobymajority.py, axelrod/strategies/memoryone.py, axelrod/strategies/retaliate.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py
We've been fast and loose with how we use `super` (myself included), and in some cases we hit the usual infinite recursion issue when a transformer is applied to a class that uses super in particular ways.
This PR corrects these issues, makes a change to the `staticmethod` testing of transformers to be more robust, and adds in a test to try to apply a transform to every strategy in the library to catch future strategy issues.
Needs to go in after #399 (for `IdentityTransformer`), tests should pass then. I did not add it to #399 since it's already got a :+1:
=> Some necessary changes for transformers to be applied to all strategies; additional test to catch implementation issues for new strategies.

axelrod/tournament_manager.py, docs/tutorials/getting_started/usage.old
stackplot should be called with the ecosystem object and not its list
this commit fixes the test and some documentation.
Change made due to these commits:
c965e249ebb8fac64e23618e80ab19deb8a6dc30
a75c52f356b1dd50910974f1bbc52b3c429dbabf
=> Fix deprecated stackplot calls

axelrod/cooperation.py, axelrod/payoff.py, axelrod/tests/unit/test_payoff.py
Adds player_count function to derive number of players from interactions dictionary
=> More refactoring of payoff.py and cooperation.py

axelrod/strategies/_strategies.py, axelrod/strategies/gobymajority.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_gobymajority.py, docs/reference/overview_of_strategies.rst
This addresses #415:
- Adds `HardGoByMajority`
- Including docs
- Also fixes memory depth for `GoByMajority` base player (was 0, should be inf).
=> 415 - Making HardGoByMajority explicit

axelrod/plot.py, axelrod/tournament_manager.py, axelrod/tournament_manager_factory.py, axelrod/utils.py, docs/tutorials/getting_started/command_line.rst, run_axelrod
Closes #420.
This is a hard one to write tests for, so here are some images that I produced. For matplotlib < 1.5:
For 1.5+
You can also now pass `-i png` (or other format) to run_axelrod down through to TournamentManager.
=> Plotting: New colormaps and image format passthrough

.travis.yml, doctest, doctests.py
@drvinceknight Think #439 but better - NOW it aggregates failures
This isn't _much_ more than a cosmetic fix, but it does mean there's One True Command to run doctests, AND it just finds all the `rst` files, rather than a dir-by-dir enumeration
=> Improved doctest discovery / runner

.travis.yml
Travis build notifcations should now appear in the activity bar in the Gitter chat room
=> Adding travis notifications to gitter chat

README.rst, docs/index.rst
I thought the landing page for the documentation isn't actually that helpful. You are met by the 3 levels of tutorials but no information about what is in them.
Here is a screenshot of what this change looks like:
What does everyone think?
=> Change depth for docs.

axelrod/strategies/__init__.py, axelrod/strategies/meta.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_meta.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/advanced/strategy_transformers.rst, docs/tutorials/further_topics/classification_of_strategies.rst
This adds the ability to make random mutations on a player (transform) **or** create a metaplayer that randomly switches between a team of players.
=> 447 - Adding a Mixed decorator **and** metaplayer

README.rst, docs/tutorials/getting_started/command_line.rst
After creating http://axelrod-tournament.readthedocs.org/en/latest/ I've made some minor tweaks to docs. This also addresses #456.
=> 431 - Minor fix of README following change to tournament repo

axelrod/tests/unit/test_tournament.py
I think Hypothesis has found a bug. I've removed the cheating strategies
which makes things work but we need to figure out why this isn't
working and revert back to testing tournaments over the whole strategy
sets.
=> Temporary fix: removing cheating strategies.

axelrod/strategies/backstabber.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_backstabber.py
This fixes the issue with mindreader and the final transformer from #465. The problem was that mindreader was reading beyond the end of the game length which causes an index error in FinalTransformer. The transformer now simply passes through the action if the tournament length is exceeded.
=> Strategy transformer fix

axelrod/strategies/backstabber.py, axelrod/strategies/mindreader.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_backstabber.py, axelrod/tests/unit/test_tournament.py
This is relevant to #465.
Seems to be an issue with MindReader + Backstabber and ThueMorse...
=> Adding in some examples for particular failures.

axelrod/strategies/_strategies.py, axelrod/strategies/gambler.py, axelrod/tests/unit/test_gambler.py, docs/reference/all_strategies.rst, docs/tutorials/further_topics/classification_of_strategies.rst
Hello axelrod people,
I have added a new strategy called PSO Gambler.
Instead of using a binary outcome for the lookup table from LookerUp class, I have run a Particle Swarm Optimisation to calculate the probability for C or D based on the lookup_table. This resulted in 6 cases where the action is randomised. 
Furthermore, It will always defect the last 2 turns (similar to the Backstabber class).
I have also added some tests, based on the lookerup, backstabber and random test suites.
Let me know if there are any problems.
I had great fun using the library.
Cheers,
Georgios
=> Added Gambler strategy

axelrod/strategies/gambler.py, axelrod/strategies/lookerup.py, axelrod/tests/unit/test_gambler.py
* Remove / Refactor redundant code between LookerUp and Gambler
* Use transformer for defection on last two rounds
* Update tests for use of the transformer (it properly handles the `tournament_length == -1` case)
* Removed redundant tests for `random_choice`
We could further refactor EvolvedLookerUp and PSOGambler but I think this is a nice balance between streamlined and readable.
@meatballs The new `Match` class doesn't set the tournament length as far as I can tell. Is that correct? We might consider adding that option as an keyword argument.
Also I think there are a few places we could refactor existing code to use the Match class, particularly in the test suite (TestHeadsUp, responses_test, maybe Mindreader's simulations).
=> Refactoring of Gambler classes to inherit from LookerUp

axelrod/tests/unit/test_utils.py, requirements.txt
- Tests for timed_message (simple)
- Tests for logger
- Adding testfixtures https://pythonhosted.org/testfixtures/logging.html It looks like this is necessary but it *does* add to the requirements.txt. Is it worth it?
Furthermore I'm not completely satisfied by the tests for the logger but
it *is* at least a test.
Note that this doesn't add a test for `run_tournament`, that's very much tested in a lot of other places and everytime we run the results but I suppose that a test would be nice. I might get to that at some point.
=> Addressing #482: some tests for utils.py

axelrod/match.py, axelrod/tests/unit/test_match.py, docs/tutorials/further_topics/creating_matches.rst
This is done with a view to clearing the way for #37 which will be made
far easier with #493.
The plan being that if a match sets the information available to players
then a probabilistic ending is just equivalent to randomly sampling the
length of the match (as I had done in the PR that this reverts) and not
letting the players know.
=> Reverting 461

.travis.yml, axelrod/strategies/geller.py
Moving module docstring to class for strategy.
Here is what it looks like locally:
=> Addressing #503

axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
This can be handled by the Multiprocessing module.
Here is a screenshot showing this working (with 8 repetitions so it definitely used the cores):
https://www.dropbox.com/s/1gzozp3vsj9mcuy/Screenshot%202016-04-03%2021.08.32.png?dl=0
I've left comments in the relevant places but these could be removed and
put in an issue to investigate the use of alternatives to the standard
multiprocessing module.
=> Fixes #516 Workers only send results back (a dictionary)

CITATION.txt, docs/citing_the_library.rst
This addresses #499. The idea of a citation file comes from: http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files
This CITATION file just points at the zenodo page.
=> Adding a citation file.

axelrod/plot.py, axelrod/tests/unit/test_tournament_manager.py, axelrod/tournament_manager.py
I use the xlabel for the heatplot as otherwise it overlapped. This was actually missing for some plots previously. As you can see I've gone for keeping things simple. About to work on #509 in which I'll make a slight tweak to have the prob end instead of the match length.
Here are some examples:
=> All plots: simple label in tnrmnt manager. Addresses #510

axelrod/__init__.py, axelrod/plot.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_tournament_manager.py, axelrod/tests/unit/test_tournament_manager_factory.py, axelrod/tests/unit/test_utils.py, axelrod/tournament_manager.py, axelrod/tournament_manager_factory.py, axelrod/utils.py, docs/tutorials/getting_started/command_line.rst, run_axelrod, test
This adds to #513 and also addresses the naming of the tournaments output by the manager as discussed here: https://github.com/Axelrod-Python/tournament/issues/27
=> Add prob end tournament type to run_axelrod

axelrod/strategies/backstabber.py, axelrod/tests/unit/test_backstabber.py, axelrod/tests/unit/test_tournament.py
DoubleCrosser says in its docstring that it defects on the last 2 rounds unconditionally but the code was defecting for the last three rounds. @uglyfruitcake confirms that the intention was for defection on the last two only.
This corrects that error and adds the use of the FinalTransformer decorator.
=> Fix DoubleCrosser and test to match description

axelrod/match.py, axelrod/match_generator.py, axelrod/player.py, axelrod/strategies/axelrod_second.py, axelrod/strategies/darwin.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/mindreader.py, axelrod/strategies/qlearner.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_match.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
#493 
This PR moves the responsibility for passing match attributes (e.g. length) from the tournament class to the match itself. (They were previously known as tournament_attributes and have also been renamed).
It doesn't add any of the potential new functionality discussed in #493.
=> Move Setting of attributes from tournament to match

setup.py
Closes #525 
Before, when running `pip install axelrod`, you needed to also install the requirements. This was potentially confusing for some reading through the installation documentation. 
Have tested this in virtual envs.
=> Adding a simple read of the requirements.txt. to setup.py

axelrod/moran.py, axelrod/tests/unit/test_moran.py
Simple PR to make the action of `reset()` in the Moran process more logical by also resetting the players.
=> Update Moran process reset method to also reset players

axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/using_the_cache.rst
Closes #547 
**This is on top of #546, so that should be merged/reviewed first. (Merging this will merge #546)**
Note that to make things in line with the match and the Moran process I've added the ability to pass a cache directly to the `Tournament` class. So the following works (as shown in the tutorial):
```
>>> cache = axl.DeterministicCache(filename)  # Read in some prebuilt cache
>>> players = [axl.GoByMajority(), axl.Alternator(), axl.Cooperator()]
>>> tournament = axl.Tournament(players, turns=200, repetitions=5, deterministic_cache=cache)
>>> results = tournament.play()
```
I haven't gotten rid of the `prebuilt_cache` argument as I didn't want to get in to the `TournamentManager` (I think that's where it's used). That could potentially be made simpler with this though?
=> Adding tutorial about cache and also ability to pass a cache directly to the tournament

.travis.yml
Closes #554 (I think?)
And we stick with the policy of the last py2.7 (for now) and the last 2 py3s?
=> Dropping support for py3.3

axelrod/tests/unit/test_strategy_transformers.py
Closes #563
This test (and the other two in `test_pickle` are testing functionality
we don't actually need.
=> Removing a test for pickling a generator

setup.py
This was causing rtd to fail:
```
...
ing build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
error: file '/home/docs/checkouts/readthedocs.org/user_builds/axelrod/checkouts/latest/run_axelrod' does not exist
Command time: 0s Return: 1
```
=> Removing the run_axelrod script from setup.

axelrod/result_set.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/advanced/reading_and_writing_interactions.rst, docs/tutorials/getting_started/interactions.rst
**This is a PR to @marcharper's `parallel` branch for #520**, (although it could actually go in to master too...).
This simplifies the interactions structure and data file format. The interactions become a dictionary mapping `index_tuples` to lists of repetitions of interactions:
```
{(0,1):[[('C', 'D'), ('D', 'C')], [('C', 'D'), ('D', 'C')]], 
(0,2):[[('C', 'C'), ('D', 'C')], [('C', 'D'), ('D', 'C')]]}
```
This "should" make it easier for you Marc to get the outcomes on a match by match basis (regardless of the order in which they are run). It should also have the tests updated/ready for you too.
HTH
=> FOR MARC: Changing the format of the interactions attribute for the tournament and result set.

axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/getting_started/tournament.rst, requirements.txt
Closes #558
This is built on top of #572.
Works for both parallel and serial. Here's a gif showing it (code from https://gist.github.com/drvinceknight/2f42efc2388f41d3da7931ffc10aee6f):
=> Adding a progress bar

axelrod/game.py, axelrod/tests/property.py, axelrod/tests/unit/test_game.py, axelrod/tests/unit/test_match.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_property.py, axelrod/tests/unit/test_tournament.py
Closes #570 
This means that instead of having to use a combination of hypothesis calls to build a tournament (for example), we can now just write:
```
@given(tournament_and_seed=@tournaments())
def test_...
```
This make no changes to the library itself.
The seed is because in that particular instance (creating a tournament) some strategy instances will use the random library when they are created so hypothesis will also let us know the random seed it used.
As well as building these things I've written tests for them and also replaced some of the tests. 
The module lives in `axelrod/tests/property.py`. Not sure if that's the best place?
=> Creating hypothesis strategies

axelrod/strategies/cycler.py, axelrod/strategies/gobymajority.py, axelrod/strategies/meta.py, axelrod/tests/unit/test_gambler.py, axelrod/tests/unit/test_gobymajority.py, axelrod/tests/unit/test_lookerup.py, axelrod/tests/unit/test_meta.py, axelrod/tests/unit/test_player.py
Closes #512 
EDIT: The main thing this does is add a test testing not only the instance classifier but also the class itself.
By default it assumes the class and instance have the same classification however I've added the ability to add to the test player a `expected_class_classifier` that can be different.
It would be worth checking that for some of the classes I've done that in a satisfactory way: I've kept the commits relatively tidy so it should be easy enough to check through those but let me know if not.
=> Adding classifier that tests classification of class as well as player

axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_tournament.py
This was causing travis to timeout on py2 (it was also hanging on py2 for my own machine).
Have reduced the size of things as well: less turns. This test just needs to check that everything runs, everything else is well tested elsewhere.
=> Make results set not build for full tournament in the integration test.

axelrod/tests/integration/test_tournament.py, axelrod/tournament.py
We lost the pass through of the noise parameter when tournament was refactored.
=> Add back in noise parameter to tournament

axelrod/match_generator.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/advanced/making_tournaments.rst
to move noise parameter into __init__
=> Refactors match_generator

axelrod/tests/integration/test_sample_tournaments.py, axelrod/tests/integration/test_tournament.py
An integration test just to confirm that the players behave as expected in probabilistic end tournaments. This ensures that the correct information is being passed (and also in a way as an integration test it checks that that one decorator is behaving as expected in this case).
Thanks Owen for pointing out that this was not at all a unit test :) 👍
=> Adding an integration test

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
Closes #617 
- Done by keeping track of the interactions in the tournament and
passing this to the ResultSetFromFile.
- If this is created by directly reading from file (so that we do not
know how many rows of data there are) then a quick count of
the size of the file is done (this is slightly inefficient but is
worth it as it gives some user feedback).
Here's a gif of it reading in the file when it's not given the size of the file (there's a small delay as it counts the size of the file):
Here's a gif of it reading it in when it's given the size of the file:
We can also call it with `progress_bar=False`:
=> Adding a progress bar to reading data.

axelrod/strategies/_strategies.py, axelrod/strategies/grudger.py, axelrod/strategies/memoryone.py, axelrod/tests/unit/test_grudger.py, axelrod/tests/unit/test_memoryone.py, axelrod/tests/unit/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
More strategies from #387 
As more people are contributing strategies from that issue I thought I might as well get these two in the library.
Am also adding another test for `Gradual` (simply one to confirm it's defined as was meant by the literature).
=> Adding soft grudger and reverse pavlov (win shift lose stay)

docs/tutorials/contributing/strategy/adding_the_new_strategy.rst, docs/tutorials/contributing/strategy/running_tests.rst
=> Correcting instructions for adding strategy to library.

axelrod/strategies/_strategies.py, axelrod/strategies/naiveprober.py, axelrod/tests/unit/test_naiveprober.py, docs/reference/overview_of_strategies.rst
Implemented as randomly defecting strategy for #379 (with a relatively small probability) which was decorated with Tit For Tat style defection using RetaliateUntilApologyTransformer. At first, I wanted to start with a Tit For Tat and decorate that with a random flip transformer, but that would flip some Ds to Cs. Is this good or maybe if I could add some better tests, it would be visible how this strategy is inaccurate?
=> Implemented a naive prober strategy (like tit for tat, but randomly defects).

axelrod/strategies/_strategies.py, docs/tutorials/advanced/classification_of_strategies.rst
#629 didn't add the strategy to the list of strategies. Pinging @314pe just so that you see where this should have been :)
=> Adding naive prober to strategies.

axelrod/strategies/_strategies.py, axelrod/strategies/prober.py, axelrod/tests/unit/test_prober.py, docs/tutorials/advanced/classification_of_strategies.rst, docs/tutorials/advanced/strategy_transformers.rst
This is the remaining strategy for the list from #387. There is another strategy on that list "contrite tft" but that strategy actually needs to know when a move against it was caused by noise. I suggest (after this) we close #387 and open another issue for that strategy as it will need a bit of a tweak to the `Match` class (or something).
Note that for some of the tests for this strategy I'm not using the helper functions. I didn't seem able to get the required behaviour with them: I got myself a big confused so found it easier to use the verbose calls. Not averse to spending time getting the helper functions working if we are keen to...
=> Adding remorseful prober

axelrod/strategies/finite_state_machines.py, axelrod/tests/integration/test_matches.py, axelrod/tests/unit/test_finite_state_machines.py
Closes #637 
This also adds an integration test that checks that repeating matches with deterministic well behaved players gives the same outcome (this is how I found #637).
This 98d1837 adds the test (which should fail assuming hypothesis stumbles on the same error I was getting locally). f263ac5949e8fc57c5b5afb0a76dd5bce825d8ec fixes the finite state machines.
=> Fixing reset method for FSMs

axelrod/strategies/_strategies.py, axelrod/strategies/finite_state_machines.py, axelrod/strategies/titfortat.py, axelrod/strategy_transformers.py, axelrod/tests/integration/test_matches.py, axelrod/tests/unit/test_finite_state_machines.py, axelrod/tests/unit/test_titfortat.py
Closes #636 
A strategy that plays like TfT if there is no noise. If there is noise and it defects because of noise (intending to cooperate), if the opponent cooperates but defects as a result of the noisy defection then it cooperates to try and bring back mutual cooperation.
Wasn't sure if there was a better way to handling the renaming from the `TrackHistoryTransformer` (without my change it adds a prefix to the strategy)?
Note that this is on top of #638 (as it needed that fix to work for the 'reduce to tft' test to work).
=> Adding contrite TfT

CITATION.rst, README.rst
Closes #641 
@meatballs fixed the Zenodo issue (https://zenodo.org/record/56203 was automatic hooked). This just reverts a change I had made so that we go back to having the zenodo badge point at the latest doi.
=> Revert "Updating zenodo badges."

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py
As suggested in #645 the csv method from the result set was removed. 
The tests that concerned csv method in `test_resultset.py` were also removed.
=> Removing csv method from Result set.

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_punisher.py, axelrod/tests/unit/test_titfortat.py
Corrected strategy from last pull request.
=> Added Slow TF2T

axelrod/__init__.py, axelrod/random_.py, axelrod/tests/integration/test_matches.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_random_.py, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/setting_a_seed.rst
Closes #651 
Firstly this adds a test to `integration/test_matches`. Simply checks that if two stochastic matches are played with the same seed they give the same result. 
Note that both the numpy and stdlib seed need to be set.
Have also added a function that sets both of those: `axelrod.set_seed` just to make it 'less easy' to only set one of the seeds...
=> 651 - Tests for random seeding and a random seeding function

axelrod/strategies/backstabber.py, axelrod/strategies/gambler.py, axelrod/strategies/titfortat.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/advanced/strategy_transformers.rst
Closes #642
This makes all transformers have the same behaviour. They need to be
called to work: previous to this, only transformers with arguments
needed to be called.
=> Implement name_prefix as opt arg for transformer

.travis.yml
(I believe) this closes #595.
It caches the hypothesis failure database. It just means that travis will keep track of parts of the test space for which tests previously failed.
=> Caching the hypothesis db.

axelrod/plot.py
=> Add warning for matplotlib in virtual env on Mac

axelrod/strategies/__init__.py, axelrod/strategies/_strategies.py, axelrod/strategies/meta.py, axelrod/tests/integration/test_matches.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_titfortat.py, axelrod/tests/unit/test_tournament.py, docs/tutorials/advanced/classification_of_strategies.rst, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/strategies.rst, docs/tutorials/contributing/strategy/adding_the_new_strategy.rst, doctests.py
Closes #664.
This renames `strategies` to `all_strategies`, and `ordinary_strategies` to `strategies`. I've kept `ordinary_strategies` in there tough just to not break anyones code. It it worth not doing that and just 'ripping off' the bandaid?
Also, @marcharper mentioned having the meta strategies in a separate list. Here I've got them **still** in the one unique list (`strategies`) but have also created another list `recursive_strategies`. We could call that `expensive_strategies` to be more generic perhaps?
Have included a tutorial also, just listing these. I ended up putting that in further capabilities.
=> Changing strategy lists

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py
=> Simplify (and correct) mean payoff diff scores

axelrod/__init__.py, axelrod/match_generator.py, axelrod/tests/property.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_property.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/further_topics/spatial_tournaments.rst
This also adds two hypothesis test decorators (for the two spatial tournaments).
=> Probabilistic ending spatial tournament.

axelrod/match_generator.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
This closes #673.
Adds various tests (mainly using hypothesis) and fixes the issue.
=> Fix noise in spatial tournaments

docs/tutorials/advanced/setting_a_seed.rst, docs/tutorials/further_topics/spatial_tournaments.rst
The previous doctests were checking particular results. When new
strategies where added to the library and/or other changes were made,
this could offset the random seed so the exact result would not
necessarily be the same.
This is the actual check we want: it checks that the results don't
change. We don't care what they actually are.
=> Add a better doctest for setting random seed.

axelrod/strategies/_strategies.py, axelrod/strategies/mutual.py, axelrod/tests/unit/test_mutual.py, docs/tutorials/advanced/classification_of_strategies.rst
Adding strategies/tests Desperate, Hopeless, Willing and Grim in mutual.py
This is a rebase of PR #683 by @ranjinidas
=> Added strategies Desperate, Willing, Hopeless, Grim

docs/reference/all_strategies.rst
Trivial: this was forgotten in #686.
=> Add autodoc for Desperate, Willing and Hopeless

.gitignore
This has caught people out on a couple of recent PRs (#697 and #693). I don't actually
know what this directory is for and/or where it comes from (never seen
it on my machine).
=> Add build directory to gitignore.

README.rst, doctests.py
Modify the `doctest` script to now test all `rst` files in the repo (now if there's python code written down it is tested to be correct).
- Minor rst syntax fix;
- Use simpler (and up to date) tournament example;
- Remove the waffle board? (Do we want this to stay in? I'm indifferent.)
=> A minor clean up of the README

.gitignore, axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, docs/tutorials/getting_started/tournament_results.rst
Addresses one part of #701
Have not added the part to write to file, thought that could be left outside of the library (users could choose to write it to csv, json etc...: once we've got the list of named tuples it's easy enough to do)? Not terribly sure though so happy enough to add it in.
At the moment I've just included the following tournament results:
- Rank
- Name
- Score
- Cooperation rating
- Wins
Easy enough to add more.
=> Add summary method to result set

appveyor.yml
You'll need to set up an account at appveyor.com.  See [these instructions](https://packaging.python.org/appveyor/#setting-up).
=> Run CI tests on Windows with Appveyor

axelrod/strategies/prober.py, axelrod/tests/unit/test_apavlov.py, axelrod/tests/unit/test_averagecopier.py, axelrod/tests/unit/test_axelrod_first.py, axelrod/tests/unit/test_prober.py
=> Fix prober tests in conjunction with test_reponses and attrs

axelrod/strategies/_strategies.py, axelrod/strategies/gradualkiller.py, axelrod/strategies/grudger.py, axelrod/tests/unit/test_gradualkiller.py, axelrod/tests/unit/test_grudger.py, axelrod/tests/unit/test_resultset.py, docs/reference/all_strategies.rst, docs/reference/bibliography.rst
EasyGo
GrudgerAlternator
GradualKiller
=> 3 New Strategies From the PRISON (http://www.lifl.fr/IPD/ipd.frame.html)

axelrod/tests/unit/test_resultset.py
In some cases floating point error will make this particular test throw
a different rank for the strategies.
=> Fix floating point error in a hyp test

axelrod/interaction_utils.py, axelrod/match.py, axelrod/tests/unit/test_interaction_utils.py
=> Issue 138 - Adds functions to calculate the state distribution of a Match

docs/reference/glossary.rst, docs/tutorials/getting_started/match.rst
Closes #712 
Any suggestion for better wording are very welcome.
=> Add description of noise in glossary and match.rst

axelrod/strategies/_strategies.py, axelrod/strategies/human.py, axelrod/tests/unit/test_human.py, docs/conf.py, docs/reference/all_strategies.rst, docs/tutorials/getting_started/human_interaction.rst, docs/tutorials/getting_started/index.rst, requirements.txt
A strategy that prompts for keyboard input rather than deriving its own action.
closes #728
=> Human Strategy

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py
Closes #723
This ensures that the ResultSet is as 'efficient' as the
ResultSetFromFile (only reading through the file or the interactions the required number of times).
=> Refactor ResultSet

axelrod/strategies/punisher.py, axelrod/strategies/qlearner.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/strategies/sequence_player.py, axelrod/strategies/titfortat.py, docs/reference/bibliography.rst
Part of issue 225. 
Documentation for a few strategies. Including various names and author.
=> Include some references and names for strategies.

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, docs/tutorials/getting_started/tournament_results.rst
Closes #738
Add state distribution and normalised state distribution to the result set.
Also adds the normalised state distribution to the summary.
=> Implement state distribution in result set.

axelrod/strategies/axelrod_first.py, axelrod/strategies/axelrod_second.py, docs/reference/bibliography.rst
Again on issue #225.
Just adding a bit to the strategies references and name for `axelrod_first.py` and `axelrod_second.py`
=> Adding to the documentation of initial Axelrod's tournaments strategies.

axelrod/strategies/_strategies.py, axelrod/strategies/prober.py, axelrod/tests/unit/test_prober.py, docs/tutorials/advanced/classification_of_strategies.rst
Related to https://github.com/Axelrod-Python/Axelrod/issues/379
=> Implement prober4 strategy from PRISON project

axelrod/strategies/_strategies.py, axelrod/strategies/doubler.py, axelrod/tests/unit/test_doubler.py, docs/reference/all_strategies.rst
Related to https://github.com/Axelrod-Python/Axelrod/issues/379
=> Implement doubler strategy from PRISON project

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
=> Implement SpitefulTitForTat strategy from PRISON

axelrod/__init__.py, axelrod/mock_player.py, axelrod/player.py, axelrod/tests/unit/test_player.py
Related to https://github.com/Axelrod-Python/Axelrod/issues/744
Add play_counts property to Player class (a dictionary counting occurrences of CC, CD, DC, DD).
Update the dictionary after each play.
Add tests for the property.
TODO:
Use play_counts property in existing strategies (e.g. Prober4, Retaliate)
=> Track CC, CD, DC, DD in Player class

axelrod/moran.py, axelrod/tests/unit/test_moran.py, docs/tutorials/getting_started/moran.rst
I also made some improvements to the Moran process implementation -- it better handles unique player types now by using the string representations of the players. In the previous implementation the process would not have distinguished between `Random(0.5)` and `Random(0.25)`, for example.
Re #754
=> Moran Process with Mutation

axelrod/strategies/__init__.py, axelrod/strategies/meta.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_meta.py, docs/tutorials/advanced/classification_of_strategies.rst
New strategy: Meta Winner Ensemble
Rather than take the "best" strategy, this MetaWinner variant chooses randomly from some of the top strategies computed each round against each opponent. In the full tournament it comes in 7th and is now the current best meta strategy.
I spent a little time tuning the parameter of how many strategies to pick from but not a lot, so it's possible that there's room for improvement.
=> Meta Winner Ensemble

.travis.yml, README.rst
=> Dropping py 2 support.

axelrod/fingerprint.py
After revising our understanding of how fingerprinting works, not all of the docs were completely updated. In a few places the docs still corresponded to our old understanding (taking the dual of the strategy instead of the probe).
=> Fix docstrings to remove any mention of Dual of Strategy

axelrod/deterministic_cache.py, axelrod/match.py, axelrod/strategies/memoryone.py, axelrod/tests/integration/test_matches.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_match.py, axelrod/tests/unit/test_memoryone.py, docs/tutorials/advanced/using_the_cache.rst
Closes #779
This makes the underlying read/write of the cache be the string repr.
The passed key is the player instances (as opposed to previously going
to have to go get the class).
=> Fixes the cache bug.

axelrod/_strategy_utils.py, axelrod/tests/unit/test_strategy_utils.py
This is possible thanks to us dropping py2 :)
=> Remove memoized for py3 caching

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py
Most are straight forward, for the creation of the points I had to
refactor things slightly (as it's a product of two lists there wasn't a
straightforward way of using tqdm on it).
Closes #768.
=> Add a variety of progress bars to the fingerprint.

axelrod/deterministic_cache.py, axelrod/strategies/__init__.py, axelrod/strategies/_filters.py, axelrod/strategies/adaptive.py, axelrod/strategies/grudger.py, axelrod/strategies/meta.py, axelrod/tests/integration/test_filtering.py, axelrod/tests/integration/test_matches.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_human.py, axelrod/tests/unit/test_meta.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_tournament.py, docs/tutorials/advanced/classification_of_strategies.rst
* Several new meta strategies
* Reworked the meta tests significantly (much simpler now I hope)
* ~~Caught some other classification related issues, and a cache issue that I haven't yet addressed (see #779)~~ now fixed
=> New meta strategies

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py, docs/reference/bibliography.rst, docs/tutorials/advanced/strategy_transformers.rst, docs/tutorials/further_topics/fingerprinting.rst
Currently fingerprinting takes classes as the target for the
fingerprint.
This was an oversight as it doesn't allow for the fingerprinting of
parametrized strategies. This allows for both.
=> Allow fingerprinting of instances.

.readthedocs.yml
This sets the python version to python 3.
You can see the docs have built properly here: http://axelrod.readthedocs.io/en/py3rtd/tutorials/further_topics/fingerprinting.html
Whereas the current master is not pointing at the new fingerprint plots: http://axelrod.readthedocs.io/en/latest/tutorials/further_topics/fingerprinting.html
=> Add a read the docs config file.

axelrod/strategies/__init__.py, axelrod/tests/unit/test_classification.py
Closes #771
Have included a very basic test and have also done some minor tidying
up.
=> Add short run time strategy list.

axelrod/moran.py, axelrod/tests/unit/test_moran.py
The Matches in the process may still be deterministic but the process itself still uses random values for the fitness proportionate selection stages.
=> Moran processes are always stochastic

axelrod/strategies/memoryone.py, axelrod/strategies/prober.py, axelrod/strategies/retaliate.py, axelrod/strategies/titfortat.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_player.py
and update some tests
Closes #476
=> Fix deprecation warnings

axelrod/strategies/_strategies.py, axelrod/strategies/finite_state_machines.py, axelrod/strategies/memoryone.py, axelrod/strategies/memorytwo.py, axelrod/strategies/prober.py, axelrod/tests/unit/test_finite_state_machines.py, axelrod/tests/unit/test_memorytwo.py, axelrod/tests/unit/test_prober.py, docs/reference/bibliography.rst, docs/tutorials/advanced/classification_of_strategies.rst
=> New Strategies: Mem2, Pun1, Collective Strategy

axelrod/result_set.py, axelrod/tests/unit/test_resultset.py, docs/tutorials/getting_started/tournament_results.rst
Keep track of the rate/count of which a
strategy cooperates in the initial round.
Closes #789.
=> Add initial play summary to the results set.

axelrod/__init__.py, axelrod/graph.py, axelrod/moran.py, axelrod/tests/unit/test_graph.py, axelrod/tests/unit/test_moran.py, docs/reference/bibliography.rst, docs/tutorials/getting_started/moran.rst
[Slides here](http://www.nimbios.org/tutorials/gametheoryfiles/evolutionary_graph_theory_back_Broom.pdf) for context.
=> Implemented the Moran process on graphs

axelrod/_strategy_utils.py, axelrod/strategies/hunter.py, axelrod/strategies/memoryone.py, axelrod/tests/unit/test_hunter.py, axelrod/tests/unit/test_prober.py
Profiling indicates that `detect_cycles` is one most expensive functions in the library, so I rewrote it and the players that use it to be more efficient (without altering their behaviors significantly).
This PR decreases tournament run time by approx 20%.
=> Update cycle detection to be more efficient

axelrod/eigen.py
Hi! I'm new to open source projects, and I thought this project would be a great place to get started. I'd love any feedback/hints/corrections/advice, especially as I'm not entirely sure I did this correctly.
=> Add type hints to eigen.py

axelrod/player.py, axelrod/strategies/adaptive.py, axelrod/strategies/ann.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/defector.py, axelrod/strategies/finite_state_machines.py, axelrod/strategies/forgiver.py, axelrod/strategies/gambler.py, axelrod/strategies/geller.py, axelrod/strategies/gobymajority.py, axelrod/strategies/gradualkiller.py, axelrod/strategies/grudger.py, axelrod/strategies/grumpy.py, axelrod/strategies/handshake.py, axelrod/strategies/hmm.py, axelrod/strategies/human.py, axelrod/strategies/lookerup.py, axelrod/strategies/memoryone.py, axelrod/strategies/meta.py, axelrod/strategies/mutual.py, axelrod/strategies/negation.py, axelrod/strategies/oncebitten.py, axelrod/strategies/prober.py, axelrod/strategies/punisher.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/strategies/sequence_player.py, axelrod/strategies/titfortat.py, axelrod/strategy_transformers.py, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst
I've eliminated the need for `@init_args` by modifying `Player.__new__` and eliminated most usage of `init_args` in the library. `Player.__new__` now caches the `args` and `kwargs` passed to `__init__`. There's no need to explicitly use the decorator except for one case in `LookerUp` where the classes are created dynamically at runtime, but it may be possible to eliminate that as well.
@meatballs This may solve your issue on #706, and if not, it should be easier to fix now.
=> Refactor Player.__new__ to automatically apply init_args

axelrod/random_.py
=> Add type hints to random

axelrod/game.py
=> Add Type hints to Game

axelrod/deterministic_cache.py
=> Add Type Hints in Deterministic Cache

axelrod/actions.py, axelrod/deterministic_cache.py, axelrod/game.py, type_tests.sh
Some of the type annotations already merged are not correct. Please be sure to run mypy on any new files with type annotations (see the included shell script). You will need to `pip install mypy`.
I was not able to get `mypy -m axelrod` to work -- it doesn't like our dynamically generated classes and I didn't track down a fix yet. (I've asked the mypy authors for advice in their gitter room.)
=> Fix Type Annotations and add type test shell script

axelrod/mock_player.py
@marcharper @drvinceknight 
Fixes part of #808 
1. Is the paramter `actions` just a list of actions? That is `List[axelrod.actions.Action]`?
2. I still don't understand what `history` is. I know it is a `list`, but of what I don't know.
3. And I think the type of `state_dist` is `collections.defaultdict`.
=> Add type hints to mock-player

axelrod/strategies/adaptive.py
#808 
Please review @drvinceknight @marcharper . I'm half certain I made a mistake.
=> Add type hints to adaptive

axelrod/strategies/alternator.py
#808 
@drvinceknight  @meatballs. Please review.
=> Add type hints to alternator

axelrod/strategies/averagecopier.py, type_tests.sh
#808 
mypy produces no errors. Same issue with the tests as #846 .
=> Add type hints to averagecopier

axelrod/plot.py, type_tests.sh
#808 
@marcharper @drvinceknight Obviously there's a lot left. But I need to discuss before attempting any further.
- The parameter `data` I think, can be list of ints, floats, etc. I think it would be better to just do `data: list`.
- The parameter `title` too can be an int, float, and object, list or anything. I can't think of way to assign a broad enough type for it.
- I think the type of the parameter `ax` is `matplotlib.axes._subplots.AxesSubplot`, although I am not sure.
- I don't understand what is `names`.
=> Add type hints for plot

axelrod/ecosystem.py
Fixes part of #808 
I have no idea what type of a variable `fitness` is. Could someone help out?
=> Add type hints for ecosystem

axelrod/strategies/better_and_better.py, type_tests.sh
#808 
@drvinceknight No errors on mypy.
=> Add type hints to better_and_better

axelrod/strategies/cooperator.py, axelrod/strategies/cycler.py, axelrod/strategies/darwin.py, type_tests.sh
#808 
`mypy` produces no error.
@drvinceknight @marcharper
=> Add type hints to cooperator, cycler, darwin

axelrod/strategies/calculator.py, type_tests.sh
#808 
No errors with mypy. @drvinceknight @marcharper
=> Add type hints to calculator

axelrod/strategies/axelrod_second.py, axelrod/strategies/backstabber.py, axelrod/strategies/defector.py, type_tests.sh
#808 
@drvinceknight @marcharper
=> Add type hints to axelrod_second, backstabber, defector

axelrod/strategies/gradualkiller.py, axelrod/strategies/grudger.py, axelrod/strategies/grumpy.py, type_tests.sh
#808 
No errors on mypy. 
@drvinceknight @marcharper
=> Add type hints to gradualkiller, grudger, grumpy

docs/reference/all_strategies.rst
This was missed in #857. 
Minor, arguably a bug.
=> Add shortmem to autodoc

setup.py
Closes #859 
Note that if you pip install with py2 you now get:
```
(py2.7) Desktop: pip install ~/src/Axelrod
Processing /home/vince/src/Axelrod
Axelrod requires Python '>=3.0' but the running Python is 2.7.12
```
=> Add py3 constraint to setup.py.

axelrod/moran.py
Reverts Axelrod-Python/Axelrod#839
On #866 it was noted that this PR actually wasn't really ready, there are a number of type test errors:
```
Axelrod(master): ./type_tests.sh      
axelrod/moran.py:34: error: The return type of "__init__" must be None
axelrod/moran.py:75: error: Need type annotation for variable
axelrod/moran.py:76: error: Need type annotation for variable
axelrod/moran.py:78: error: Need type annotation for variable
axelrod/moran.py:79: error: Need type annotation for variable
axelrod/moran.py:116: error: Cannot determine type of 'players'
axelrod/moran.py:122: error: Cannot determine type of 'players'
axelrod/moran.py:132: error: Cannot determine type of 'players'
axelrod/moran.py:142: error: "Tuple[str]" has no attribute "pop"
axelrod/moran.py:144: error: Argument 1 …
```
=> Revert "Add type for Moran"

axelrod/strategies/geller.py, axelrod/strategies/hunter.py, axelrod/strategies/memorytwo.py, type_tests.sh
#808
Only one error on mypy for `hunter.py`.
`axelrod/strategies/hunter.py:107: error: Need type annotation for variable`
I think this is an error with mypy where it can't infer type for empty containers. See [here](https://github.com/python/mypy/issues/1534).
=> Add type hints to geller, hunter, memorytwo

axelrod/interaction_utils.py, axelrod/result_set.py, axelrod/tests/unit/test_interaction_utils.py, axelrod/tests/unit/test_resultset.py, docs/tutorials/getting_started/tournament_results.rst
Add two functions to interaction_utils:
- `interaction_utils.compute_state_to_action_distribution`: computes
list of counter objects of mapping a `(state, action)` to a count.
- `interaction_utils.compute_normalised_state_to_action_distribution`: computes
list of counter objects of mapping a `(state, action)` to a normalised
count (for a given state).
There have then been incorporated in `axelrod.result_set` and in particular in
the `result_set.summarise()` output. Which now includes the average
rates for each strategy in a tournament. So for memory 1 strategies this
means we can measure their parameters and for non memory 1 strategies we
can infer what the parameters correspond to the data.
=> Add state to action analysis.

axelrod/strategies/_strategies.py, axelrod/strategies/verybad.py, axelrod/tests/unit/test_verybad.py, docs/reference/all_strategies.rst
#379 
Here is the [paper](http://abricom.org.br/wp-content/uploads/2016/03/bricsccicbic2013_submission_202.pdf) . Page 3.
=> Add strategy VeryBad

docs/tutorials/contributing/strategy/docstrings.rst, docs/tutorials/contributing/strategy/index.rst
=> [MRG+1] Documentation on docstrings requirements

axelrod/mock_player.py, axelrod/player.py, axelrod/strategies/apavlov.py, axelrod/strategies/appeaser.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/finite_state_machines.py, axelrod/strategies/hmm.py, axelrod/strategies/punisher.py, axelrod/strategies/qlearner.py, axelrod/strategies/stalker.py, axelrod/strategies/titfortat.py, axelrod/tests/unit/test_calculator.py, axelrod/tests/unit/test_grumpy.py, axelrod/tests/unit/test_human.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_memorytwo.py, axelrod/tests/unit/test_meta.py, axelrod/tests/unit/test_mock_player.py, axelrod/tests/unit/test_player.py, axelrod/tests/unit/test_punisher.py, axelrod/tests/unit/test_rand.py, axelrod/tests/unit/test_stalker.py, axelrod/tests/unit/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst, docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
Addresses #874 with a tweaked testing framework.
The `versus_test` method removes the option to set player histories and can be used to test strategies (and player attributes during matches) by creating a match between the player in question and an opponent.
The opponent can either be an actual player from the library or is defined as a cycle by a passed sequence of actions (there are examples of this in the docs and `test_titfortat.py`).
I've refactored all the tests in `test_titfortat.py` (which is now one module that raises no warnings).
When/if we're happy with this as a suggestion, we should open an issue about refactoring all the tests to use this approach. (This would be a big/important piece of work so we should ask for small contributions at a time to make sure we don't miss …
=> Add a versus_test method to TestPlayer

axelrod/mock_player.py, axelrod/strategies/apavlov.py, axelrod/tests/unit/test_deterministic_cache.py
=> Correction to deterministic cache test

axelrod/deterministic_cache.py
The exception in line 120 of deterministic_cache.py can never be thrown and is therefore impossible to test and so I've removed the entire try/except block.
Caught by coverage report
=> Remove redundant try except block

axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py
Add a missing test picked up by coverage report and fix the bug it then uncovered.
=> Strategy transformer tests

axelrod/tests/strategies/test_apavlov.py
Also: pushed coverage to 100%.
Have added more test cases and also removed a special case that is now
tested with the versus test.
=> Refactor apavlov for #884.

axelrod/strategies/averagecopier.py, axelrod/tests/strategies/test_averagecopier.py
Note that I think I've caught a bug here:
The average copier was using integer division for the calculation of the
opponent's cooperation ratio. So it was in effect either 0 or 1. I've
fixed this and also written tests that show the behaviour changes for
different seeds (in essence testing that the behaviour is stochastic).
=> Refactor averagecopier for 884 and a bug.

axelrod/strategies/backstabber.py, axelrod/tests/strategies/test_backstabber.py
added tests.
also refactored backstabber and fixed an off-by-one error. 
#884
=> issue#844 backstabber.py

axelrod/strategies/verybad.py, axelrod/tests/strategies/test_verybad.py
Awesome project - I'm currently working my way through Coursera's Game Theory course and found this repository after listening to the recent Talk Python podcast episode.
**Changes**
- refactors tests.strategies.test_verybad to my understanding of https://github.com/Axelrod-Python/Axelrod/issues/884 & [readthedocs](http://axelrod.readthedocs.io/en/latest/tutorials/contributing/strategy/writing_test_for_the_new_strategy.html)
- from my understanding of expected behavior, this fixes a miscalculation when checking if the move is one of the first three
- a few whitespace / pep8 related changes to these two files
Looking forward to feedback and potentially diving deeper into this project.
=> 884: VeryBad

axelrod/strategies/inverse.py, axelrod/tests/strategies/test_inverse.py
https://github.com/Axelrod-Python/Axelrod/issues/884
**Changes**
- move test_inverse.py to versus_test testing strategy
- fix last defect computation - I believe this was incorrectly calculating the index of the opponent's first defect and never changing. I've changed this logic to traverse the opponent's history beginning at the end of the array moving backwards instead of the front.
=> 884-inverse

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
Strategy from PRISON(1998) that plays C twice for opening. If opponent plays same move twice in a row, the player mimics that move, otherwise just plays it's previous move.
'slow_tft' from PRISON list in #379
=> Add SlowTitForTwoTats2 Strategy

axelrod/strategies/_strategies.py, axelrod/strategies/grudger.py, axelrod/tests/strategies/test_grudger.py
A generalization of the SoftGrudger strategy. SoftGrudger punishes by playing: D, D, D, D, C, C. after a defection by the opponent.  GeneralSoftGrudger only punishes after its opponent defects a specified amount of times consecutively (parameter "n"). The punishment is in the form of a series of defections (parameter "d") followed by a 'penance' of a series of consecutive cooperations (parameter "c").
SoftGrudger (already existed) is "soft spiteful" from the PRISON list in #379 and this is a generalization of that strategy.
=> Add GeneralSoftGrudger Strategy

axelrod/tests/unit/test_property.py
This should hopefully stop sporadic failures on travis (due to
timeouts) - mentioned on #935
=> Implement a minimal prob end for property test

axelrod/_strategy_utils.py, axelrod/actions.py, axelrod/strategies/cooperator.py, axelrod/strategies/cycler.py, axelrod/tests/strategies/test_better_and_better.py, axelrod/tests/strategies/test_calculator.py, axelrod/tests/strategies/test_cooperator.py, axelrod/tests/strategies/test_cycler.py, axelrod/tests/strategies/test_player.py, axelrod/tests/unit/test_actions.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_strategy_utils.py
#884 
Cycler depended on knowing that Actions.C and Actions.D were 'C' and 'D'. I wrote a few lines to refactor that and can remove them with ease.
=> 844 b and c

axelrod/strategies/ann.py, axelrod/strategies/apavlov.py
#808 
In ann.py, I am not really sure what the type of `weights` is supposed to be. I think it should be a list, but it could also be an numpy array? Any other iterable?
In meta.py , What is `team`'s type supposed to be?
I am not sure, but I think these are the last of the strategies to add type hints to.
=> Add type hints to ann, meta

axelrod/strategies/human.py, axelrod/tests/strategies/test_human.py
=> Override the repr for the Human strategy.

axelrod/__init__.py, axelrod/moran.py, axelrod/random_.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_random_.py, docs/tutorials/getting_started/moran.rst
Closes #842 
Adds an approximate Moran process that can take a sample of match outcomes (so that these are not rerun every time).
This also makes a `random_.Pdf` class available, which is a generic probability distribution function with a `sample` method (could be useful elsewhere).
=> 842 - Approximate Moran Process

docs/tutorials/further_topics/approximate_moran_processes.rst, docs/tutorials/further_topics/index.rst, docs/tutorials/further_topics/moran_processes_on_graphs.rst, docs/tutorials/getting_started/moran.rst
This closes #961 
I've also grabbed the commit from #960.
=> Fragment/streamline the Moran process beginning documentation

axelrod/strategy_transformers.py, axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_strategy_transformers.py
Our transformers were not reclassifying the strategies (mostly we weren't trying but in one case we were but it was not tested and not working). See #971 
This implements the ability to pass a `reclassifier` function to the strategy transformer factory so that we can reclassify based on input parameters (for example if using the Noisy transformer but passing noise of `0` or `1` then the classifier does not change). 
I've also written such reclassifiers for all relevant transformers EDIT: ~~although technically the Mixed strategy transformer isn't as smart as it could be but I suggest this gets merged under the bug fix rule and an issue gets opened for that transformer. (I've set it to blankly say that it make strategies stochastic which is what we want for any sensible use case).~~ I've …
=> Fix bug in classification of transformers

axelrod/strategies/_strategies.py, axelrod/strategies/resurrection.py, axelrod/tests/strategies/test_resurrection.py, docs/tutorials/advanced/classification_of_strategies.rst
The PR adds DoubleResurrection strategy to Axelrod. 
I have added a WIP tag to check if the tests pass properly.
=> [WIP] Add DoubleResurrection strategy

axelrod/strategies/_strategies.py
We missed this on #876. (Arguably this is a bug)
=> Add double resurrection to strategies list.

axelrod/player.py, axelrod/strategies/qlearner.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_calculator.py, axelrod/tests/strategies/test_memorytwo.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_qlearner.py, axelrod/tests/strategies/test_titfortat.py, axelrod/tests/unit/test_match_generator.py, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/player_equality.rst
- Add equality method and tests to player.
- Add documentation for player equality.
- Refactored some other tests to make use of this method
- Refactor a match generator test which was failing as a result of the
eq method. Previously this was testing equality of instance.
Some other minor changes I've made as a result of this:
- Change when qlearner makes random choice. I've also removed the reset
test. This is now being tested by the parent test class for all
strategies.
- Fix small bug in contrite. Without this, contrite was not resetting
correctly (the recorded history was being maintained in the class
attribute).
This closes #885 but also closes #940 which was worked on a while ago
but which has not seen any progress.
=> Implement an eq method for players

.travis.yml, docs/reference/all_strategies.rst, run_mypy.py, run_strategy_indexer.py
Closes #957. I am expecting this to fail on travis: two modules are not currently indexed (`hmm` and `memorytwo`). Using that as a test that this script works (once travis fails, will push the fix).
=> Add strategy index test to travis.

axelrod/tests/strategies/test_handshake.py
=> Refactor tests for handshake.

requirements.txt, rtd_environment.yml
This no longer seems to be necessary. (It fixed a bug related to a version #584)
=> Remove pin of pyparsing.

axelrod/strategies/finite_state_machines.py, docs/reference/bibliography.rst
=> Add bibliographic references for fsm strategies.

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_titfortat.py, docs/reference/bibliography.rst, docs/tutorials/advanced/classification_of_strategies.rst
Strategy is adapted from http://lesswrong.com/lw/7f2/prisoners_dilemma_tournament_results/
=> Add Alexei strategy

axelrod/strategies/gradualkiller.py, axelrod/strategies/stalker.py, axelrod/strategy_transformers.py, axelrod/tests/unit/test_strategy_transformers.py, docs/reference/bibliography.rst, docs/tutorials/further_topics/spatial_tournaments.rst
Currently our docstrings get overwritten for a number of strategies.
For example the Alexei strategy's docstring does not appear (as the
class written passes through a transformer):
http://axelrod.readthedocs.io/en/latest/reference/all_strategies.html#axelrod.strategies.titfortat.Alexei
(Here is the source code for Alexei:
http://axelrod.readthedocs.io/en/latest/_modules/axelrod/strategies/titfortat.html#Alexei
This ensures the original docstring is kept and also fixes a couple of
errors that then appeared in the docstrings.
=> Ensure that transformers do not overwrite docstrings

appveyor.yml, axelrod/player.py, axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_first.py, axelrod/tests/strategies/test_axelrod_first.py, docs/conf.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst, requirements.txt
#379 
New Strategy to be implemented
Please tell e also how to fix the test problem ;)
Thank you
=> SteinAndRapoport Strategy

docs/conf.py
Closes #1019 (hopefully for good, if not we'll go back to using a conda env). Marking this as a bug as technically it is (our master branch docs are failing to build) and it'll hopefully stop @meatballs and I getting emails from rtd...
Here's a passed build: https://readthedocs.org/projects/axelrod/builds/5454913/
=> Add tqdm to mocking for docs.

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
Adds a new strategy EugineNier.
Source here- http://lesswrong.com/lw/7f2/prisoners_dilemma_tournament_results/
=> Add EugineNier strategy from LessWrong

axelrod/strategies/punisher.py, axelrod/tests/strategies/test_punisher.py
=> Refactor tests for punisher.

axelrod/strategies/prober.py, axelrod/tests/strategies/test_prober.py
Addresses #884
Also reformats strategy docstrings (which addresses #225).
=> Refactor tests for Prober.

axelrod/tests/strategies/test_oncebitten.py
=> Refactor tests for oncebitten

axelrod/strategies/_strategies.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
Adds the new strategy DynamicTwoTitsForTat, based off of the TwoTitsForTat stategy by adding a probability of forgiveness based off of the ratio of the opponent's cooperations to total moves (so their rough probability of cooperation).
Link to original request: https://github.com/Axelrod-Python/Axelrod/pull/1027
=> Add a new DynamicTwoTitsForTat strategy

axelrod/tests/strategies/test_mathematicalconstants.py
=> Refactor tests for mathematical constant

axelrod/tests/strategies/test_memorytwo.py
Addresses #884.
Some of the test cases were not reproducible (they relied on impossible histories) but what I've got there does test everything (I believe!) and I'm also now carefully checking the attributes.
=> Refactor memory two test.

axelrod/tests/strategies/test_axelrod_first.py, axelrod/tests/strategies/test_hunter.py, axelrod/tests/strategies/test_player.py
=> Refactor tests for hunter.

axelrod/player.py, axelrod/tests/strategies/test_player.py
This is a minor refactor of some warnings that were occurring:
- A `simulate_play` that was using a fake history;
- A warning from the generator equality
The change to the way the generator equality was being run is based on
this error:
```
.........../home/vince/src/Axelrod/axelrod/player.py:165:
PendingDeprecationWarning: generator 'Player.__eq__.<locals>.<genexpr>'
raised StopIteration
for _ in range(200))):
```
Addresses #884
=> Refactor tests for player.

axelrod/strategies/memoryone.py, axelrod/tests/strategies/test_memoryone.py, docs/reference/bibliography.rst
Addresses #884 
I also added some references to strategies.
=> Refactor tests for memory one

axelrod/__init__.py, axelrod/graph.py, axelrod/moran.py, axelrod/tests/unit/test_graph.py, axelrod/tests/unit/test_moran.py, docs/tutorials/further_topics/moran_processes_on_graphs.rst, docs/tutorials/getting_started/moran.rst
Use spatial Moran Processes throughout. 
Also add ability to pass a prob_end to the Matches.
In terms of performance this actually seems faster:
```
%%timeit
for players in [[axl.Cooperator()] * 3 + [axl.Defector()] * 3,
[axl.Random(), axl.Grudger(), axl.TitFor2Tats()],
[s() for s in axl.demo_strategies]]:
for seed in range(100):
axl.seed(seed)
mp = axl.MoranProcess(players)
mp.play()
winner = mp.winning_strategy_name
```
output: `1 loop, best of 3: 8.7 s per loop`
whereas current `master`:
```
%%timeit
for players in [[axl.Cooperator()] * 3 + [axl.Defector()] * 3,
[axl.Random(), axl.Grudger(), axl.TitFor2Tats()],
[s() for s in axl.demo_strategies]]:
for seed in range(100):
axl.seed(seed)
mp = axl.MoranProcess(players)
mp.play()
winner = mp.winning_strategy_name
```
Output: `1 loop, best …
=> Reconcile Moran processes

axelrod/__init__.py, axelrod/actions.py, axelrod/player.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/axelrod_second.py, axelrod/strategies/negation.py, axelrod/strategy_transformers.py, axelrod/tests/strategies/test_calculator.py, axelrod/tests/unit/test_actions.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/further_topics/noisy_tournaments.rst
=> removed flip_action, now use C.flip() and D.flip()

axelrod/strategies/dbs.py, axelrod/tests/strategies/test_dbs.py, axelrod/tests/unit/test_classification.py, docs/tutorials/advanced/classification_of_strategies.rst
This is in fact a strategy with significant run time:
https://github.com/Axelrod-Python/Axelrod-notebooks/pull/13
=> Re classify run time for dbs.

axelrod/strategies/grudger.py, axelrod/tests/strategies/test_grudger.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/unit/test_classification.py, axelrod/tests/unit/test_strategy_transformers.py, docs/tutorials/advanced/classification_of_strategies.rst
Reclassify. Had to adjust some tests:
- Expected classification ones in doctests and classification tests.
- Adjust a test for a meta player.
- Change some tests for reclassification of transformers (that used
Grudger as an example).
Closes #1064
=> Change Grudger mem depth to 1.

axelrod/strategies/lookerup.py
The rewrite of lookerup broke pyswarm training. This line change is necessary to fix it.
=> Update lookerup init parameter check

axelrod/strategies/_strategies.py, axelrod/strategies/memoryone.py, axelrod/tests/strategies/test_memoryone.py, docs/reference/bibliography.rst
Closes #1069
This is just wrapper for the Memory One Player.
- Write tests for Reactive strategy.
- Add a Reactive strategy.
=> Add a Reactive Strategy.

README.rst
Here's my streamlining of the README - discussions at #1047. I had it lying around and think it's better than the status quo.
You can view it here: https://github.com/Axelrod-Python/Axelrod/blob/readme-revamp/README.rst
=> Streamline the README

docs/tutorials/advanced/strategy_transformers.rst
i came across these while working on pickling transformed strategies.  the `:code:` name does not match the strategy transformers class's name.
=> likely typo in strategy_transformers.rst

docs/tutorials/further_topics/fingerprinting.rst, docs/tutorials/getting_started/interactions.rst
I assume this was being skipped because of output ordering. Hopefully
CI is still happy on all py versions.
=> Fix a bug that was being skipped.

axelrod/plot.py, axelrod/tests/unit/test_plot.py
Closes #1085
This doesn't fix that issue so to speak although it does just fix
matplotlib as a strict requirement. The current check does not work.
=> Remove check for matplotlib installed

setup.py
Currently when we pip install axelrod we also install hypothesis.
This is however only used for development. I've added a tweak to the
setup.py file to just remove it from the read in requirements.
I don't think we need to adjust the contributing documentation as `pip
install -r requirements` will still install hypothesis.
=> Remove hypothesis from setup.

axelrod/strategies/axelrod_first.py
The LaTeX doesn't render as intended now that this has been moved to the
docstring (it wasn't probably overkill anyway):
http://axelrod.readthedocs.io/en/stable/reference/all_strategies.html#axelrod.strategies.axelrod_first.Grofman
=> Fix minor typo in docstring.

axelrod/match_generator.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, docs/tutorials/advanced/index.rst, docs/tutorials/advanced/player_information.rst
It is possible to pass a dictionary to `axelrod.Match` is
`match_attributes` which correspond to the information given to players.
This is motivated by wanting to reproduce Axelrod's second tournament in
which all matches were 1 of 5 values.
=> Add ability to pass match attributes in tournament

axelrod/tests/strategies/test_darwin.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_selfsteem.py, axelrod/tests/strategies/test_stalker.py
We were only playing against Random, @marcharper found and fixed a bug via
hypothesis on it here:
https://github.com/Axelrod-Python/Axelrod/pull/1097
This catches the bug too:
```
Axelrod(pass-match-attributes) ✗: python -m unittest
axelrod.tests.strategies.test_titfortat
...............................................................................F................................................................
======================================================================
FAIL: test_reset_history_and_attributes
(axelrod.tests.strategies.test_titfortat.TestNTitsForMTats)
Make sure resetting works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
File
"/home/vince/src/Axelrod/axelrod/tests/strategies/test_player.p …
```
=> Improve our test for reset and fix some test bugs.

axelrod/strategies/axelrod_second.py, docs/reference/overview_of_strategies.rst
The docstring text (from the original paper) and the K61R code in axelrod-fortran both test whether the cooperation rate is less than 0.6.
We use the defection rate, so the equivalent condition should test whether it is greater than or equal to 0.6
In the current implementation, it is simply testing whether the defection rate is greater than 0.6
=> Alter inequality condition to match docstring

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
This is the implementation of the K76R Fortran strategy mentioned in #1102. The strategy was named Gladstein after the author's last name.
=> Gladstein strategy

axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py
I have tested this locally with axelrod_fortran and this strategy now
agrees with the fortran version against all basic strategies.
Closes #1112
=> Fix a small bug in Gladstein.

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_first.py, axelrod/tests/strategies/test_axelrod_first.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
This is the implementation of Tideman and Chieruzzi's strategy from Axelrod's first tournament. 
Resolves #1105.
=> TidemanAndChieruzzi strategy

axelrod/tests/strategies/test_titfortat.py, docs/tutorials/contributing/strategy/writing_test_for_the_new_strategy.rst
This is an aesthetic change: `match_attributes={"length": -1}` is
equivalent (from the code's pov) to `match_attributes={"length:
float("inf")}`.
=> Change unknown match lengths in tests.

axelrod/player.py, axelrod/strategies/axelrod_first.py, axelrod/strategies/cooperator.py, axelrod/strategies/cycler.py, axelrod/strategies/dbs.py, axelrod/strategies/gobymajority.py, axelrod/strategies/memoryone.py, axelrod/strategies/rand.py, axelrod/strategies/retaliate.py, axelrod/strategies/selfsteem.py, axelrod/strategies/sequence_player.py, axelrod/strategies/stalker.py, axelrod/strategies/titfortat.py, axelrod/strategies/zero_determinant.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_stalker.py, axelrod/tests/strategies/test_zero_determinant.py
=> Properly handle recieve_match_attributes for Stalker, simplify for LR Players, and various style fixes

.travis.yml, docs/tutorials/contributing/strategy/writing_the_new_strategy.rst
Note we only need to do this when the inputs from the match are used to
change some other variable.
Some other minor tweaks here:
- Remove unneeded data file.
This was checked in at some point but shouldn't have been.
- Remove outdated documentation about repr.
This is now done automatically by the parent class.
- Make some minor stylistic changes.
- PEP8 (column width)
- Change to use class hyperlink instead of code syntax highlighting.
=> Write description/ex of `receive_match_attributes`

axelrod/plot.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_tournament.py, axelrod/tournament.py, requirements.txt
This closes #1129.
I could not find anything in the release notes
<http://matplotlib.org/users/whats_new.html> however I think this is due to the fact that mpl 2.1 got rid of the ability to handle the unflattened sub list (so this fix will still work with previous versions of mpl).
=> Fix the data set dimensions for the sdvplot.

axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/tutorials/advanced/classification_of_strategies.rst
Currently champion uses a linear scale to adapt its two "phases" for any
game length. This was not the intention of the original description and
is causing errors with comparisons of the original results.
This essentially simplifies the strategy.
(I believe this was my doing)
=> Correct the implementation of Champion.

docs/reference/overview_of_strategies.rst
The original FORTRAN strategy k46r is the strategy called Eatherley in the library.
Original submitted by Graham Eatherley. The description can be found in Axelrod's second tournament
paper.
Updated #1095 and I did run the fingerprints to make sure that the strategies match:
**k46r fingerprints:**
**Eatherley fingerprints:**
=> add Eatherley reference to k46r.

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
Strategy submitted to Axelrod's second tournament by Charles Kluepfel (K32R).
=>  Implemented K32R by Charles Kluepfel.

axelrod/fingerprint.py
As reported by @gaffney2010, it is possible that the rows of the
cooperation rate array are now longer in order (I believe this to
happen on python < 3.6 because of ordering of dicts). This simple fix
ensures that this doesn't happen.
=> Sort the internal data.

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst
=> Added strategy Borufsen/k42r from Axelrod's second tourn

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
=> Implemented strategy Cave (k49r from Axelrod's Second)

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, axelrod/tests/strategies/test_meta.py, docs/reference/overview_of_strategies.rst
Fingerprint below.
Some notes about the translation from Fortran:  The Fortran cycles through these three states, labeled by `ICASE`.  I replaced the third state with a flag, called `forgive_flag`.  The first two states, it goes back and forth between these as the opponent Defects; when the opponent eventually Cooperates, this strategy goes to state three (raises the `forgive_flag`) if and only if it's in the second state at that point (i.e. there have been an odd number of Defects since last Cooperate).  I wrote the code to replace the first two states with a parity-check on the number of Defects between Cooperates, which I call `defect_padding`.  This reworking should make it a little clearer, and draws out the infinite memory depth that wasn't clear with the original code.
=> Implemented Weiner, k41r from Axelrod's Second

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
Below are the fingerprints for the basic strategies, the random, and against the six custom strategies that I used in the test file.
I've also attached a PDF that bridges the gap from the Fortran to what I have, along with some small amount of commentary on the code.
[HarringtonNotes.pdf](https://github.com/Axelrod-Python/Axelrod/files/1527303/HarringtonNotes.pdf)
=> Implemented Harrington (k75r from Axelrod's Second)

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst
FPs below.
This was similar in some ways to TidemanAndChieruzzi from the first tournament, so I tried to make my function implementation similar to the that one.
The biggest change in my refactoring was to change the way JDR was used, by calculating this as a triangle number:  https://github.com/Axelrod-Python/TourExec/blob/v0.3.0/src/strategies/k84r.f#L18
=> Implemented MoreTidemanAndChieruzzi, K84R from Axelrod's second

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/tutorials/advanced/classification_of_strategies.rst
Short and simple one.
https://github.com/Axelrod-Python/TourExec/blob/v0.2.0/src/strategies/k35r.f
FPs:
=> Implement Getzler, K35R from Axelrod's second.

axelrod/strategies/axelrod_first.py, axelrod/tests/strategies/test_axelrod_first.py
This closes #1149.
Fixed implementation (by altering line 676) as suggested on the issue.
Tweaked tests to make sure they pass.
=> fixes implementation error in TidemanAndChieruzzi

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
Fingerprints below.
Pretty direct translation.  Their funny if statements reduced a lot.
IF (J1 * J .EQ. 1) GOTO 540
J1 and J
IF (J2 * 2 + J1 + J * 2 + J .EQ. 1) GOTO 550
J2 cannot be 1, because then the whole left side would exceed 1.  Ditto J.  So this becomes J1=1.
IF (J2 * 2 + J1 * 2 + J .EQ. 1) GOTO 560
Similarly J1 and J2 must equal zero.  So this becomes J=1.
=> Implemented Leyvraz, K86R from Axelrod's second

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst
Fingerprints below.
Notes on refactor from https://github.com/Axelrod-Python/TourExec/blob/v0.3.0/src/strategies/k72r.f :
N, M, and JCOUNT are all integers, so everything gets rounded.  So the probability statement (line 12) actually only ever gets run with 0% or 100% (evidenced by the basic-strategy fingerprints).  And actually unless the if-statement in line 11 gets run, then the probability statement always Cooperates, since JCOUNT can be at most M-1.
=> Implemented White strategy, k72r from Axelrod's Second

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
=> Implemented Black, K83R from Axelrod's Second

axelrod/strategies/axelrod_first.py, axelrod/strategies/geller.py, axelrod/strategies/mindreader.py, axelrod/strategies/titfortat.py, axelrod/tests/strategies/test_axelrod_first.py, axelrod/tests/strategies/test_geller.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_mindreader.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_titfortat.py, docs/tutorials/advanced/classification_of_strategies.rst
This writes a test that verifies that the memory depth given in `player.classifier` is an upper bound.
It's done using a hypothesis test that only checks a single set of 5 opponents each time so it's not overly expensive (still benefiting from hypothesis's failure database).
This is the commit that writes the test: e9da4f9
Note that it picked up a few mis classifications, that I've fixed here (I'm actually surprised it wasn't more):
- c612c1e: `DynamicTwoTitsForTat` (strategy makes use of the cooperation count, so it's infinite memory)
- f6479f7: `RandomTitForTat`: classified correctly, I've just tweaked the implementation.
- ef130c2: `SteinAndRapoport`: defects on last two rounds: so it's infinite memory.
- 483d96e: all the cheating strategies had different (weird/negative) memory …
=> Add test for memory depth

README.rst, docs/tutorials/getting_started/installation.rst, setup.py
This ensures that if you pip install axelrod with an unsupported verion
of python that you get an error message:
```
(test-axelrod-on-3.4) ~: pip install ~/src/Axelrod
Processing ./src/Axelrod
Axelrod requires Python '>=3.5' but the running Python is 3.4.5
```
=> Add lower bound for python in setup.

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst
Fingerprints below.
The refactoring is somewhat straight-forward with the exception of https://github.com/Axelrod-Python/TourExec/blob/v0.3.0/src/strategies/k64r.f#L30.  Here, I refactored as
P = |E-F|, but E+F = M-1, so that P = |2E+1-M|.  Then 10*P < M iff P/(2M) < 0.05.  Equivalently, |(E+0.5)/M - 0.5| < 0.05.  I called (E+0.5)/M as `portion_defect` and bounded by 0.45 and 0.55.
Also a little different is I update history _before_ deciding on a move, so to emulate the Fortan (which does after), I wait until the third turn to start (instead of the second) and look back one extra turn.
I think count_them_us_them was intended to be indexed by them_three_ago, us_two_ago, them_last, so that it predicts the opponent's next turn.  It kind of predicts the opponents last move instead...  [If …
=> Implemented Yamachi, k64r from Axelrod's Second.

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/tutorials/advanced/classification_of_strategies.rst
Simple strategy.  I implemented as a FSM.  Fingerprints below.
=> Implemented Colbert, K51R from Axelrod's Second.

axelrod/strategies/memoryone.py, axelrod/strategies/zero_determinant.py, axelrod/tests/strategies/test_memoryone.py
This closes issue #1169.
The issue has been that if `four_vector` was not set the player would not
break. This is fixed by having a default `four_vector` which corresponds
to the strategy Win-Stay Lose-Shift. Note that when this happens a
warning message is raised to let the user know (using the library
warnings).
A test has been altered to test that the default values are passed correctly.
Test: `test_default_if_four_vector_not_set`.
An issue has been that the players that inherited from `MemoryOnePlayer`
were breaking. This was because several classes were initialising with
an empty vector and were setting the vector are retrieving information
on the game.
This was addressed using the function `get_initial_four_vector`, which
will only set a default and raise an error for the general …
=> Fixes initialisation bug for memory one

axelrod/strategies/memoryone.py
While working on the memory two strategies we observed that when creating the transition rates dict of the strategy there as a float argument. 
The argument seems to have been left there by previous versions, thus I am removing it.
=> remove float from memory one

axelrod/fingerprint.py, axelrod/moran.py, axelrod/strategies/apavlov.py, axelrod/strategies/darwin.py, axelrod/strategies/hunter.py, axelrod/strategies/memoryone.py, axelrod/tests/unit/test_moran.py, axelrod/tournament.py
Closes #1176
Various things I've needed to do:
- In a number of places include that the type is `Optional[]`.
- In a number of places include an `assert` so that `mypy` knows that
the type is no longer None.
- I have made a minor refactor to the Moran process, I could have used
asserts but this actually pointed out a spot where I believe the tests
were incorrect: we were testing a specific situation where
`MoranProcess.birth` or `MoranProcess.death` should have been called with
default `index=None` but was actually being tested with `index=0`.
- **I have ignored** a type hint check in `fingerprint.py`: I was
completely unable to get this one happy
To ensure that any new PRs don't break CI let's merge this under bug fix. :+1: :)
=> Fix type hints for mypy 2.1

axelrod/strategies/_strategies.py, axelrod/strategies/punisher.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_punisher.py
I picked up #1132 which implements a strategy called Tricky Level Punisher. 
The `pr` was failing due a division by zero error. Moreover, I had to tweak the tests of `MetaMajorityLongMemory` because now `TrickyLevelPunisher` is in the strategy's team.
```
>> import axelrod as axl
>> player = axl.MetaMajorityLongMemory()
>> tricky = axl.TrickyLevelPunisher()
>> tricky in player.team
True
```
Note that this `pr` will fail due to #1176, I will rebase once #1177 is merged.
=> Add Tricky Level Punisher

setup.py
For the old pypi our project description was automatically read in from
`README.rst`. This is no longer the case:
https://pypi.org/project/Axelrod/
I believe this fixes it.
=> Fix the long description for new pypi

requirements.txt
This is related to #1183 . Currently a clean install of Axelrod will fail because of backwards incompatible change to `prompt_toolkit` version 2+. This pins `prompt_toolkit`.
(I suggest we merge this but leave #1182 open as a place holder, there's no rush with unpinning `prompt_toolkit` as ipython pins this too I believe: https://github.com/ipython/ipython/blob/master/setup.py#L193.)
=> Pin prompt toolkit because of backwards comp.

axelrod/strategies/lookerup.py, axelrod/tests/strategies/test_geller.py
Closes #1185
Currently, the lookerup players pop from a list of initial plays. This
breaks when playing against the cheating players which simulate their
play (as the list of initial players no longer exists).
This fixes that by ensuring the list of initial plays does not
disappear which I think technically is probably better behaviour anyway?
=> Modify/fix initial play of lookerup players.

axelrod/action.py, axelrod/tests/unit/test_actions.py
* Improves docstrings and move to numpydoc format
* Reviewed unit tests and add a few edge cases
=> Spruce up actions module

axelrod/deterministic_cache.py, axelrod/tests/unit/test_deterministic_cache.py
Next bit for #347.
This includes several things:
* Improved (hopefully) docstrings and a module docstring with a little example
* Moved cache key helper functions to module level - these were static methods so it felt natural to move them out of the class... but I'm not 100% there was a reason for doing this. If so, I can move back, although `@staticmethod` IMO is best used sparingly.
* Refactored unit tests to test public API instead of the internal helper funcs. Again, assumed this is a good thing, but not 100% there wasn't some decision to test internal functions throughout the library.
=> Spruce up deterministic_cache

axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_plot.py, doctests.py, matplotlibrc
EDIT: ~~I have also added some comments to ensure we do not reorder these
imports.~~
=> Add a matplotlibrc

axelrod/ecosystem.py, axelrod/eigen.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_ecosystem.py, axelrod/tests/unit/test_eigen.py
Next batch for #347 
* Minor improvements to docstrings and unit tests for ecosystem
* Simplified unit tests for deterministic_cache a little bit more
* Minor edits to eigen module, and made several function internal
=> Spruce up deterministic_cache, ecosystem and eigen

axelrod/moran.py, axelrod/tests/unit/test_moran.py, docs/reference/bibliography.rst, docs/tutorials/getting_started/moran.rst
Using a fitness function that scales the utility for the Moran process is commonly used in the literature. 
This `PR` implements that feature and now the Moran process has a new argument, the `fitness_function` which is set as `None` as a default. 
I added a test which tests that cooperators can take over a population of defectors when the selection is weak. Also added an example in the documentations.
Please note that after chatting with @drvinceknight,  I run `black` and `isort` on the files 
(commit 4919dd2). This might make the diffs more complicated than needed, please let me know if you want me to undo that :+1: .
=> Pass fitness function moran process

axelrod/action.py, axelrod/tests/unit/test_actions.py
This enables sorting Actions for [https://github.com/Axelrod-Python/axelrod-dojo/pull/50](https://github.com/Axelrod-Python/axelrod-dojo/pull/50).
=> Define a total order for Action

.travis.yml
I am able to build the docs locally using sphinx `v1.7.8`.
After wiping the build on readthedocs they built correclty
(https://docs.readthedocs.io/en/latest/guides/wipe-environment.html).
I have added a `make clean` to `.travis.yml` so that travis now tests
that it can build a completely clean set of docs.
Closes #1202
=> Unpin sphinx on travis.

axelrod/fingerprint.py, axelrod/tests/unit/test_fingerprint.py
* Prefix internal functions and methods with underscore
* Test the external API only
* Be more locally explicit in unit tests (no need for
=> Spruce up fingerprint (mostly AshlockFingerprint)

axelrod/game.py, axelrod/tests/unit/test_game.py
=> Spruce up game and its tests

axelrod/graph.py, axelrod/moran.py, axelrod/tests/unit/test_graph.py
Continuation of #347.
Major changes:
- Change add_edge and add_edges to be internal since they're not used anywhere else
- Turned edges and vertices into properties
- Broke up unit tests into several classes
- Grouped and deduped unit test cases for Graph
- Added some coverage for untested methods (in_vertices, etc.)
=> Sprice up graph and its unit tests

README.rst, citations.md
Add new citations to the list and redirect the reader to citations.md in the README
=> Closes #1211

axelrod/game.py, axelrod/strategies/_strategies.py, axelrod/strategies/adaptor.py, axelrod/strategies/bush_mosteller.py, axelrod/tests/strategies/test_adaptor.py, axelrod/tests/strategies/test_memoryone.py, axelrod/tests/strategies/test_meta.py, docs/reference/all_strategies.rst, docs/reference/bibliography.rst, docs/tutorials/advanced/classification_of_strategies.rst
Implements two strategies from [this paper](https://pdfs.semanticscholar.org/4656/7ef01c0554ce903595005f605f9f6bea6808.pdf)
* I wasn't able to reproducible Table 5 in the paper (see the tests) but otherwise it looks ok to me.
* Both strategies were named Adaptor in the paper
* ~This PR is based on top of #1212~
=> New Strategy: Implementation of Adaptor

axelrod/strategies/human.py, axelrod/tests/strategies/test_human.py, requirements.txt
As of today, some systems work with prompt_toolkit v1 by default, but
Arch Linux has migrated to v2, and it's the last version on PyPI
To maintain the Arch Linux package of this library, it was required to
revert the 8dba4c0 commit, yet that didn't suffice to make the Human
class work in that system
This commit changes the Human strategy to work on environments with
either prompt_toolkit versions, the main differences are:
- Human._history_toolbar no longer return a list with a tuple, but
just the raw content (making its tests more straightforward)
- self.status_messages["toolbar"] is a function as expected by the
prompt_toolkit version available
Although the "pygments.toolbar" string is there when using the
prompt_toolkit v2, the "pygments" library isn't a dependency, since
using the …
=> Make Human work w/ both prompt_toolkit v1 and v2

axelrod/deterministic_cache.py, axelrod/match.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_match.py, docs/tutorials/advanced/using_the_cache.rst
The caching is inefficient when prob_end is used.  The current paradigm caches by players and number of turns in match, for non-stochastic.  But this ignores the fact that you can read a shorter match from the result of a longer match.  For example if we have a 20-turn match cached, and we wish to run a 19-turn match, we COULD just read the first 19 moves from the 20-turn match, but the current paradigm would completely re-run because no 19-turn match has been run yet.
I changed the code to
1. Cache on player-pairs only.
2. Only re-run a match if the cache is shorter than the desired match.  In that case overwrite the cached value.
3. Sliced the cached value after reading, so as to get the first n moves, as desired.
I ran the code below and found an 80% speed-up.  I don't think this adds …
=> Speed up caching logic

axelrod/strategies/shortmem.py, axelrod/tests/integration/test_filtering.py, axelrod/tests/integration/test_matches.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/strategies/test_ann.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_shortmem.py, axelrod/tests/unit/test_filters.py, axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_game.py, axelrod/tests/unit/test_match_generator.py, axelrod/tests/unit/test_moran.py, axelrod/tests/unit/test_pickling.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_property.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_strategy_transformers.py, axelrod/tests/unit/test_tournament.py, requirements.txt
The first commit removes the hypothesis decorator kwarg `max_iterations` that give deprecation warnings (and are reported as no-ops). I changed hypothesis to be pinned at >= 3.2 instead of ==.  [Edit: see below, also limited to <=3.68] See #1214 .
The second commit reduces the run time of some of the longer tests.  These changes cut the local total test run time down by 65% (excluding doctests, which take about 60 seconds to run). For example some tests now avoid the Meta strategies (like the filter set tests). Others now only test a random sample of strategies. (We may need to add some random seeding.) There are still tests that run larger tournaments so I think the risk for this change is low.
Also, I marked one test as skippable if the matplotlib version is 3+, and removed the …
=> Hypothesis warnings and speed up some tests

axelrod/action.py, axelrod/tests/unit/test_actions.py
On profiling a tournament I noticed that the removed functions were among the most often called. It turns out that they are unnecessary because Enums provide their own `__hash__` and `__eq__`. This PR speeds up actual tournaments by 20-25% in my (limited) testing.
=> Remove redundant member functions of the Action class

axelrod/compute_finite_state_machine_memory.py, axelrod/tests/unit/test_compute_finite_state_machine_memory.py
In using, I uncovered a bug. Basically memory-zero and memory-one cases need to be handled specially. I was checking this case with a condition on the number of memit-pairs, but in fact a memory-one strategy could have a long chain memit-pairs that all suggest the same set of reactions.
So I fixed this, and added a test that would have caught this error.
I created a copy of #1242, because I'm bad at git.
=> Fix memory-one error in compute FSM memory

axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py
Happened to catch this bug in an old strategy I submitted.
It didn't match the logic here.
https://github.com/Axelrod-Python/TourExec/blob/master/src/strategies/k32r.f
Shouldn't come up often.  It's difficult to construct an example that would have caught this.
=> Fix bug in Kluepfel strategy

axelrod/strategies/_strategies.py, axelrod/strategies/axelrod_second.py, axelrod/tests/strategies/test_axelrod_second.py, docs/reference/overview_of_strategies.rst, docs/tutorials/advanced/classification_of_strategies.rst
Adapted from https://github.com/Axelrod-Python/TourExec/blob/v0.3.0/src/strategies/k58r.f
Here are some fingerprints for this new strategy and for the existing Fortran strategy:
=> Added Appold (k88r) strategy from Axelrod's second.

axelrod/evolvable_player.py, axelrod/tests/strategies/test_evolvable_player.py
for easier inclusion in CSV files (as used in axelrod-dojo).
=> Change EvolvablePlayer serialization to write strings instead of bytes

docs/tutorials/further_topics/evolvable_players.rst
This ensures the `doctest: +SKIP` does not appear.
=> Fix rendering of code snippet in docs.

axelrod/strategies/_strategies.py, axelrod/strategies/prober.py, axelrod/tests/strategies/test_prober.py, docs/reference/bibliography.rst
It's an implementation of the "Detective" prober strategy as described in "The Evolution of Trust" game created by Nicky Case in July 2017
https://ncase.me/trust/
In the game, it's implemented in:
https://github.com/ncase/trust/blob/8ff91b81358d02847f81eaa46a797e806e749178/js/sims/PD.js#L217
This strategy was referenced in #813, and it's the only one in the Nicky Case game that wasn't already implemented in this library.
=> Add Detective strategy from Nicky Case game

doctests.py
Added Numpy Style documentation to the file, and a small side-note about the ELLIPSIS option from doctest online documentation.
=> Added documentation to the doctests.py

axelrod/strategies/_strategies.py, axelrod/strategies/grudger.py, axelrod/strategies/oncebitten.py, axelrod/tests/strategies/test_meta.py, axelrod/tests/strategies/test_oncebitten.py
Hello everyone,
While working on one of my projects I realised that the strategy `Fool Me Forever`, which is an original strategy implemented within the library, is actually the same as the strategy `EasyGo` from
[Prison1998 and Li2011](https://axelrod.readthedocs.io/en/stable/reference/bibliography.html#li2011).
Source code for `Fool me Forever` (link to source code [here](https://axelrod.readthedocs.io/en/stable/_modules/axelrod/strategies/oncebitten.html#FoolMeForever)):
```python
@staticmethod
def strategy(opponent: Player) -> Action:
if opponent.defections > 0:
return C
return D
```
Source code for `EasyGo` (link to source code [here](https://axelrod.readthedocs.io/en/stable/_modules/axelrod/strategies/grudger.html#EasyGo)):
```python
@staticmethod
def strategy(opponent: Player) -> …
```
=> Removes Fool Me Forever

axelrod/strategies/axelrod_first.py
=> Update FirstBy Downing for #1285

axelrod/result_set.py
=> Suppress expected numpy warnings

axelrod/load_data_.py, axelrod/plot.py, axelrod/tests/integration/test_tournament.py, axelrod/tests/unit/test_deterministic_cache.py, axelrod/tests/unit/test_fingerprint.py, axelrod/tests/unit/test_load_data.py, axelrod/tests/unit/test_plot.py, axelrod/tests/unit/test_resultset.py, axelrod/tests/unit/test_tournament.py, requirements.txt
A lot of the file reads and writes are causing me problems because my IDE tries to run logic from the location where the file is located, and the code is written to only be run from the top-level directory.  I could see a new user being thrown by this too.
This change makes paths a little more robust, by accounting for the path the user is actually in.
=> Create function to handle relative paths

docs/conf.py
Closes #1311 
You can see the build on https://axelrod.readthedocs.io/en/fix-documentation/reference/overview_of_strategies.html#beaufils-et-al-s-tournament-1997
This is a bug fix, I'll do a new release once it's in.
=> Mock yaml in documentation for rtd

docs/index.rst
Running `len(axelrod.strategies)` gives 235 :)
Genuinely not sure if I've got my grammar right in this sentence so please do suggest something else. I just wanted to bump the number :)
=> Update the nbr of strategies in first page of docs

axelrod/strategies/revised_downing.py, axelrod/tests/strategies/test_revised_downing.py
Fixes https://github.com/Axelrod-Python/Axelrod/issues/1279
It looks like when the fortran was translated to python, PAST was changed to self.history[-1]. Because of where it's set in the fortran, it should actually be self.history[-2].
https://github.com/Axelrod-Python/TourExec/blob/master/src/strategies/K59R.f#L35
https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/revised_downing.py#L55
This was tested with axelrod_fortran.
=> Fix RevisedDowning

axelrod/tests/strategies/test_gambler.py, axelrod/tests/strategies/test_lookerup.py, axelrod/tests/strategies/test_player.py, axelrod/tests/strategies/test_titfortat.py
classifier_test in test_player was using dictionaries instead of the Classifiers class.  This error was masked because all classifiers currently match the dictionaries.  In the future, we will use formulas for some of the classifiers.
In addition to the changes on test_player, I removed some lines which altered expected classifiers to incorrect values.  These lines accounted for the fact that the memory_depth was sometimes set on initializing.  The new Classifiers paradigm can account for this.
=> Change classifier test to call Classifiers

docs/tutorials/contributing/running_tests.rst
After removing from requirements, hypothesis isn't automatically installed.  This may cause confusion, especially since we require a very specific version of hypothesis.  Here I add a note in the Running Tests documentation.
=> Add documentation about hypothesis

axelrod/data/all_classifiers.yml, axelrod/deleteme.py, axelrod/strategies/mindreader.py, axelrod/tests/strategies/test_mindreader.py
The MindReader strategies appear to use game (line 44), so I add this to the classifier.
=> Fix makes_use_of on MindReader

axelrod/tests/ultimatum/tests.py, axelrod/ultimatum/player.py, requirements.txt
Did a few cleanup tasks and expanded to 100% coverage.
Specially I:
- Added tests
- Deleted set_match_attributes for now.
- Changed name/repr on AcceptanceThresholdPlayer.  It looks like this was a copy-paste error.
- Typed remaining inputs/outputs
- Added default values to strategies, to be consistent with IPD where every strategy is trivially initializable.
- Uncommented distribution strategy
- Changed tests to assertTrue/assertFalse (for boolean tests) and assertAlmostEqual for testing equality of floats.  I think these are best practices.
- Use attrs library instead of namedtuple, to address the commen there - I really love this library.
=> Cleanup ultimatum and expand coverage

axelrod/tests/ultimatum/tests.py, axelrod/ultimatum/player.py
Added a strategy I made up called BinarySearchOfferPlayer.  I want to have a simple player that uses history in some way.
In addition, I:
- Added super().__init__() where missing.  Otherwise will fail to initialize history (I think).
- Added "source" to docstrings.  In future changes I plan to add a few strategies from research and want to keep track of that.  We can maybe change to "names" later to be consistent with Axelrod IPD strategies.
- Fixed PlayerPosition type error in Outcome.  I think marcharper was trying to tell me that I had a bug in my previous commit but I missed it.
- Refactored a common "offer" function to be reused.
=> Add BinarySearchOfferPlayer to ultimatum

axelrod/game_params.py, axelrod/match.py, axelrod/player.py, axelrod/tests/ultimatum/tests.py, axelrod/ultimatum/player.py
I modify Match to take a "GameParams" object.  A GameParams class is intended to eventually include everything that a Match or Tournament needs to know about a new game type (IPD, ultimatum, etc.).  For now it includes only a few functions used in Match play, described below.  This change is non-API breaking, because Match takes ipd_game_params by default.
GameParams is a class with three elements, all functions passed at initialization:
- generate_play_params: Generates a "PlayParams" object, which tells Match how to play a single round.  (For now, this is players with their positions.)  This is an iterator which should produce all the PlayParams needed for the entire Match run.  It takes in a list of players and the number of desired rounds.
- play_round:  From PlayParams and a Game …
=> Add GameParams to make Match generalizable

axelrod/game.py, axelrod/game_params.py, axelrod/ipd_params.py, axelrod/match.py, axelrod/prototypes.py, axelrod/tests/ultimatum/test_game.py, axelrod/ultimatum/game.py
Creates a scorer (or "Game") for ultimatum.  This is one of the inputs to Matches and Tournaments, so it's needed to run an ultimatum tournament.
I would have liked to have done a couple of things differently:
1. Move scorer to belong to game_params.  Remove scorer as an input to Matches and Tournaments and Moran processes and Match Generators, preferring instead to pass around game_params.  (game_params would need to be more carefully initialized so that scorer objects aren't shared.)  The advantage of this approach is 1) it makes it impossible to mix-and-match scorers and game types (an issue I've ignored for now), and 2) it centralizes all the _settings_ for a game type.
2. Have the scorer's score function take in a dictionary of Actions keyed by position and return a dictionary of …
=> Create a scorer for ultimatum

axelrod/classifier.py, axelrod/game.py, axelrod/game_params.py, axelrod/ipd_params.py, axelrod/player.py, axelrod/prototypes.py, axelrod/tests/integration/test_ultimatum_match.py, axelrod/tests/ultimatum/test_game_params.py, axelrod/tests/unit/test_pickling.py, axelrod/ultimatum/game_params.py, axelrod/ultimatum/player.py, axelrod/ultimatum/strategies.py, docs/reference/adding_games.rst, docs/reference/index.rst
After defining game_params for ultimatum, we can run a Match.  I added an integration test which does this.
I added some TODOs to track things I want to circle back to, and I added more docstrings to all the new files, following marcharper's request on the last PR.
I added an "adding_games" document in our documentation, which outlines all the things that need to be addressed when we create a new game.  This is a bit of stub and will need to be expanded, but want to use it to keep track of all the changes I'm making.
=> Add ultimatum game_params, and extend documentation.

axelrod/data/all_classifiers.yml, axelrod/strategies/memoryone.py, axelrod/strategies/memorytwo.py, axelrod/tests/strategies/test_memoryone.py, axelrod/tests/strategies/test_memorytwo.py
The memoryone and memorytwo strategy files were doing some unusual things in the test files.  It seems like they were trying to duplicate some functionality in Player's repr and in TestPlayers tests.  This was causing problems with Classifiers logic.  Details:
Code was changing name on initialization to include the parameter that the strategy was used with.  name is only used in two places:  for __repr__ and for Classifiers.  __repr__ already attaches the initialization parameters, and Classifiers was getting messed up because instances had a different name than the class.  By making this change we make the strategy behave consistently with other strategies.
I removed test_name from these unittests because this is covered by test_repr in TestPlayer.  It's true that test_play in these …
=> Standardize tests for memoryone and memorytwo files.

axelrod/tests/integration/test_names.py, docs/tutorials/advanced/classification_of_strategies.rst
Test 'test_all_strategies_have_names' is always passed because when a strategy has no name, it adopts the name attribute from the 'Player' class.
=> Modify test to ensure that all strategies have names

.github/workflows/config.yml, axelrod/tests/integration/test_filtering.py, docs/tutorials/advanced/tournament_results.rst
Currently `test_boolean_filtering` only uses strategies as given by the `strategy_list` hypothesis strategy. This by default only picks short run time strategies so we are not ensuring that the long run filter works.
=> Add a long-run strategy to the filtering test

axelrod/tests/unit/test_tournament.py, docs/tutorials/contributing/guidelines.rst, docs/tutorials/contributing/index.rst, docs/tutorials/contributing/running_tests.rst, docs/tutorials/contributing/setting_up_the_environment.rst
This is related to #1352.
Once this PR is merged we should:
- Change github default branch to `dev`
- Delete `master`
- Confirm that read the docs is looking at `release`
Am I missing anything?
We should also remove the release process information from the wiki
(assuming we're happy with what I've written here).
Finally, once #1360 is done we should make sure we update the docs with
the relevant information.
=> Write a new documentation page with branch info
